### ISSUE TITLE
Digital product support

### ISSUE THREAD

**Issue by krahamath** [avored/laravel-ecommerce#124]
Please add digital product support, 
1. Add migration for product table with following column: product_type: digital(1)/physical(2).
2. Digital or downloadable formats pdf and zip
3. Download link should be custom generation and it should own to purchased users only with their email(SALT/ECRYPT)

**Comment by indpurvesh** [comment]
This feature is in queue already.

**Comment by indpurvesh** [comment]
Downloadable Product support has been added. Thanks
