### ISSUE TITLE
Register Admin

### ISSUE THREAD

**Issue by juniorfrogie** [avored/laravel-ecommerce#131]
How can I register admin user?

**Comment by indpurvesh** [comment]
@juniorfrogie You will create an Admin User during an installation Step.

**Comment by juniorfrogie** [comment]
@indpurvesh I tried localhost:8000/install but it appears 'Sorry, the page you are looking for could not be found.'

**Comment by indpurvesh** [comment]
Are you using an `php artisan serve` command?

**Comment by juniorfrogie** [comment]
@indpurvesh  I solved by uncomment these lines in app.php
AvoRed\Install\Module::class,
AvoRed\Ecommerce\Provider::class,

**Comment by indpurvesh** [comment]
Thanks i think i know where the bug is. Thanks again.

**Comment by juniorfrogie** [comment]
@indpurvesh run into error when goto http://localhost:8000/admin/login

ErrorException (E_WARNING)
Illegal offset type in isset or empty

if (isset($this->customCreators[$config['driver']])) {
            return $this->callCustomCreator($name, $config);
        }
 
do you have any idea?

**Comment by indpurvesh** [comment]
Bug comes  from yesterday few commit that i did. So if you replace the code into `config\auth.php` file like below would possibly fix the bug.


    return [
    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */
    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'admin' => [
            'driver' => 'session',
            'provider' => 'admin-users',
        ],
        'api' => [
            'driver' => 'passport',
            'provider' => 'admin-users',
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => AvoRed\Ecommerce\Models\Database\User::class,
        ],
        'admin-users' => [
            'driver' => 'eloquent',
            'model' => AvoRed\Ecommerce\Models\Database\AdminUser::class,
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | Here you may set the options for resetting passwords including the view
    | that is your password reset e-mail. You may also set the name of the
    | table that maintains all of the reset tokens for your application.
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */
    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
        'adminusers' => [
            'provider' => 'admin-users',
            'table' => 'admin_password_resets',
            'expire' => 60,
        ],
    ],
    ]

**Comment by juniorfrogie** [comment]
@indpurvesh replace with your code but still got the same error

**Comment by juniorfrogie** [comment]
@indpurvesh 
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => AvoRed\Ecommerce\Models\Database\User::class,
    ], ...

but in folder modules/avored/ecommerce/* there is no folder models

**Comment by indpurvesh** [comment]
it will look up the file into src folder so path should be.

`modules/avored/ecommerce/src/Models/Database`

**Comment by indpurvesh** [comment]
@juniorfrogie 
If you delete and do a fresh installation should fixed the bug.
