### ISSUE TITLE
Paypal module?

### ISSUE THREAD

**Issue by gstamosbg** [avored/laravel-ecommerce#132]
Hi guys. I am interested to make a paypal payment module.. but i cant figure where is a payments in order form? How to add somethink new different than strip. 🔢 

Peace ^^ :*

**Comment by indpurvesh** [comment]
I give you some starting point for creating an paypal module.

# How to create a Paypal Module

You can start by creating a module base files.

    php artisan avored:module:make Gstamos Paypal

You can register payment option inside your `Module.php` file

    use AvoRed\Framework\Payment\Facade as PaymentFacade;
    use Gstamos\Paypal\Payment as PaypalPayment;

    public function boot() {
        $paypal = new PaypalPayment();
        PaymentFacade::put($paypal->identifier(), $paypal);
    }


You can create an Payment file `Paypal.php` inside your src file.

    <?php

    namespace Gstamos\Paypal;

    use AvoRed\Framework\Payment\Payment as PaymentEcommerce;
    use AvoRed\Framework\Payment\Contracts\Payment as PaymentContracts;

    class Payment extends AbstractPayment implements PaymentContract
    {

    /**
     * Identifier for this Payment options
     *
     * @var string
     *
     */
    protected $identifier = "gstamos-paypal";

    /**
     * Title for this Payment options
     *
     * @var string
     *
     */
    protected $name = "Pay by Paypal";

    /**
     * Payment options View Path
     *
     * @var string
     *
     */
    protected $view = "gstamos-paypal::payment.index";



    /**
     * Get Identifier for this Payment options
     *
     * return string
     *
     */
    public function identifier()
    {
        return $this->identifier;
    }

    /**
     * Is this Payment Option Enabled?
     *
     * return boolean
     *
     */
    public function enable()
    {
        return true;
    }


    /**
     * Get Title for this Payment Option
     *
     * return boolean
     *
     */
    public function name()
    {
        return $this->name;
    }

    /**
     * Payment Option View Path
     *
     * return String
     *
     */
    public function view()
    {
        return $this->view;
    }

      /**
      * Payment Option View Data
      *
      * return Array
      *
      */
     public function with()
     { 
         return [];
     }

    /*
     * Process Payment Calculation
     *
     */
    public function process($orderData, $cartProducts, $request)
    {
        //EXECUTE API here if any??
 
        return true;

    }
    }

**Comment by gstamosbg** [comment]
Interesting.. When i add in boot()         
```
$paypal = new PaypalPaymentt();
        PaymentFacade::put($paypal->identifier(), $paypal);
```

i am receiving a error :

`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Gstamos\Paypal\Payment' not found
 `

**Comment by indpurvesh** [comment]
Just a Question @gstamosbg 
Are you trying to create your own Module?

**Comment by gstamosbg** [comment]
Yep but i dont know what i am doing wrong :D

**Comment by indpurvesh** [comment]
avored:module:make Gstamos Paypal

When you execute these command in your base directory it will create basic folder structure for your module.

open a file in `modules/gstamos/paypal/src/Module.php` it will contain `boot` method.

Then you create a `modules/gstamos/paypal/src/Payment.php` and code sample for the file is above.

**Comment by gstamosbg** [comment]
Oh dude... i saw:

> You can create an Payment file Paypal.php inside your src file.

And totally messed the thinks.. now is ok :) and also i was added one `'` in end of the file... need to sleep hahaha. Thanks alot :)
