### ISSUE TITLE
When edit some Admin account, page got not found.

### ISSUE THREAD

**Issue by Steven0811** [avored/laravel-ecommerce#134]
<img width="457" alt="screen shot 2018-03-22 at 9 49 00 pm" src="https://user-images.githubusercontent.com/4948562/37774333-e0758204-2e1a-11e8-86ec-23c1a8176c10.png">

click edit then...
<img width="1103" alt="screen shot 2018-03-22 at 9 49 05 pm" src="https://user-images.githubusercontent.com/4948562/37774335-e1b5f798-2e1a-11e8-944b-2c977137c6a3.png">

**Comment by indpurvesh** [comment]
@Steven0811 i can't replicate the bug. Do you like to re install and try again?
