### ISSUE TITLE
Brand name changes

### ISSUE THREAD

**Issue by krahamath** [avored/laravel-ecommerce#136]
I suggest you to make the your brand name like professional and easy to write and read by make them smaller case. Ex. Avored [not AvoRed] and See this: https://screenshots.firefox.com/5SoZUIdXRBw8GJFu/www.avored.com also this http://prntscr.com/j149p2

Hope you will like in the smaller case of RED

**Comment by indpurvesh** [comment]
@krahamath It's a good idea.

**Comment by krahamath** [comment]
Which is done?
