### ISSUE TITLE
fresh installed, and got error when access product single page.

### ISSUE THREAD

**Issue by dimasip** [avored/laravel-ecommerce#138]
No hint path defined for [avored-related]. (View: E:\xampp\htdocs\laravel-ecommerce\themes\avored\default\views\product\view.blade.php)

**Comment by dimasip** [comment]
E:\xampp\htdocs\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php
    }
 
    /**
     * Get the segments of a template with a named path.
     *
     * @param  string  $name
     * @return array
     *
     * @throws \InvalidArgumentException
     */
    protected function parseNamespaceSegments($name)
    {
        $segments = explode(static::HINT_PATH_DELIMITER, $name);
 
        if (count($segments) != 2) {
            throw new InvalidArgumentException("View [{$name}] has an invalid name.");
        }
 
        if (! isset($this->hints[$segments[0]])) {
            throw new InvalidArgumentException("No hint path defined for [{$segments[0]}].");
        }
 
        return $segments;
    }
 
    /**
     * Find the given view in the list of paths.
     *
     * @param  string  $name
     * @param  array   $paths
     * @return string
     *
     * @throws \InvalidArgumentException
     */
    protected function findInPaths($name, $paths)
    {
        foreach ((array) $paths as $path) {
            foreach ($this->getPossibleViewFiles($name) as $file) {
                if ($this->files->exists($viewPath = $path.'/'.$file)) {
                    return $viewPath;
Arguments
"No hint path defined for [avored-related]. (View: E:\xampp\htdocs\laravel-ecommerce\themes\avored\default\views\product\view.blade.php)"

**Comment by dimasip** [comment]
try to remove;
                @include("avored-related::related.product.list")
                @include("avored-review::product.review")

and finally works, now i try to figure out problem of both @include files.

**Comment by dimasip** [comment]
update:
i try to change
@include("avored-related::related.product.list")
@include("avored-review::product.review")

to

@include("avored::related.product.list")
@include("avored::product.review")

and now works like a charm.

**Comment by indpurvesh** [comment]
@dimasip Just add below line into composer.json and run 'composer update' it should fix the problem.

    "require": {
        "avored/framework": "dev-master",
        "avored/related" : "dev-master",
    }

then execute 

    composer update

**Comment by Axahox** [comment]
I got the same issue and updating composer didn't work so i removed :

> @include("avored-review::product.review")

It seems to refer to nothing and i actually didn't find any other file using "avored-review" or the targetted file, so I assumed it was an oversight.
