### ISSUE TITLE
PDO Exception during install

### ISSUE THREAD

**Issue by G00sfraba** [avored/laravel-ecommerce#139]
Illuminate\Database\QueryException  : SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'configuration_value' at row 1 (SQL: insert into `avored_configurations` (`configuration_key`, `configuration_value`, `updated_at`, `created_at`) values (general_site_description, AvoRed is a free open-source e-commerce application development platform written in PHP based on Laravel. Its an ingenuous and modular e-commerce that is easily customizable according to your needs, with a modern responsive mobile friendly interface as default, 2018-05-01 16:07:57, 2018-05-01 16:07:57))

PDOException::("SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'configuration_value' at row 1")

**Comment by indpurvesh** [comment]
Thanks @G00sfraba 

I have increase length for the table field to 999 so it should be ok. Thanks for raising the bug.
