### ISSUE TITLE
Many bugs in new version

### ISSUE THREAD

**Issue by ItisAhsan** [avored/laravel-ecommerce#140]
-first after a fresh install it throws when opening the site it throws error undefined variable categories in nav.blade.php
-can't open the category it throws bad method exception

**Comment by indpurvesh** [comment]
@ItisAhsan to me it seems like you using a version 2.0 and rest other modules with latest dev-master because current nav.blade.php file doesn't contain any $categories variable.

do you want to reinstall it with below command. (make sure you use --stability=dev) 

    composer create-project avored/laravel-ecommerce --stability=dev
