### ISSUE TITLE
Add new payment method

### ISSUE THREAD

**Issue by mahdi7abash** [avored/laravel-ecommerce#146]
Hi 
First i want to thank your for this good ecommerce website you made ,but i can't place order to finish what i added to cart the and where to add shipment cost ?? 
Thanks

**Comment by indpurvesh** [comment]
If you enabled at least one payment and one shipping method in backend then you should be able to place an order.

i just added an another `fixed-rate` module for fixed rate shipping cost. you can simply installed it via

    composer require avored/fixed-rate

Thanks @mahdi7abash

**Comment by mahdi7abash** [comment]
@indpurvesh  Thanks shipping options added successfully , but payment options pick from store Says the option field is required ..  and I don't need to add payment stripe where to add payment pick up such as cash on delivery 
Appreciate your support

**Comment by indpurvesh** [comment]
I haven’t done cash on delivery module but soon I will make one too

**Comment by mahdi7abash** [comment]
@indpurvesh  Ok thanks but if there any other method or how to create it since stripe not abled in my country lebanon

**Comment by indpurvesh** [comment]
[AvoRed Cash on Delivery ](https://github.com/avored/cash-on-delivery)

Let me know now you can do checkout or not?

**Comment by mahdi7abash** [comment]
Not yet

**Comment by indpurvesh** [comment]
Add below line to your `composer.json` file 

    "avored/cash-on-delivery" : "dev-master"

then do `composer update`.

Go to Admin=>system=>configuration 

enabled Yes for Cash On Delivery then you can see an cash on delivery option in front end.

**Comment by mahdi7abash** [comment]
Cash on delivery added successfully 
Now i can do place order ,
But on admin under orders when i try to change status  from pending to succes or delivered and same issue when try to send email invoice swift_TransportExpception ( process could not be started the system cannot find the path ) 
 Thanks you very much for your great support i really appreciate your help 
And also let me ask you more question 
If i want to add more payment method same way you add right ?   
And if i want to add create product or special product how would i add second button beside create product under shop / product 
Thanks in advance

**Comment by indpurvesh** [comment]
The error you are received is because you never setup your Email SMTP setting.

follow this laravel docs regarding how to setup mail in laravel

https://laravel.com/docs/5.6/mail

Yes you can follow the same structure to add another payment gateway
