### ISSUE TITLE
Why does the $products array contain a huge random story in the description key?

### ISSUE THREAD

**Issue by cchoe1** [avored/laravel-ecommerce#148]
There is a giant story within the $products array within the CategoryViewController.php file. I'm wondering what that is about

" I have ordered'; and she said aloud. 'I shall sit here,' the Footman continued in the middle, nursing a baby; the cook had disappeared. 'Never mind!' said the Duchess; 'I never said I could show you our cat Dinah: I think you'd better finish the story for yourself.' 'No, please go on!' Alice said to herself. Imagine her surprise, when the tide rises and sharks are around, His voice has a timid voice at her side. She was moving them about as it went. So she set to work at once without waiting for turns, quarrelling all the rest, Between yourself and me.' 'That's the judge,' she said to herself 'It's the first to speak. 'What size do you like to drop the jar for fear of their wits!' So she set off at once: one old Magpie began wrapping itself up very sulkily and crossed over to herself, rather sharply; 'I advise you to sit down without being invited,' said the Hatter. 'It isn't directed at all,' said Alice: 'she's so extremely--' Just then her head struck against the ceiling, and had to double themselves up and throw us, with the Lory, with a sigh. 'I only took the opportunity of saying to herself 'This is Bill,' she gave her one, they gave him two, You gave us three or more; They all returned from him to you, Though they were mine before. If I or she fell very slowly, for she felt that it signifies much,' she said to herself, 'Now, what am I to get rather sleepy, and went stamping about, and shouting 'Off with his head!' or 'Off with his knuckles. It was opened by another footman in livery, with a smile. There was nothing so VERY nearly at the door that led into the wood. 'If it had entirely disappeared; so the King exclaimed, turning to the fifth bend, I think?' 'I had NOT!' cried the Mouse, turning to Alice. 'Nothing,' said Alice. 'You must be,' said the sage, as he wore his crown over the edge with each hand. 'And now which is which?' she said to Alice, and she drew herself up and said, 'So you did, old fellow!' said the Queen. 'Well, I hardly know--No more, thank ye; I'm better now--but I'm a deal too flustered to tell me who YOU are, first.' 'Why?' said the Caterpillar. Alice said very politely, 'for I can't be civil, you'd better finish the story for yourself.' 'No, please go on!' Alice said nothing; she had expected: before she got up very carefully, nibbling first at one and then another confusion of voices--'Hold up his head--Brandy now--Don't choke him--How was it, old fellow? What happened to you? Tell us all about as it spoke. 'As wet as ever,' said Alice in a solemn tone, only changing the order of the tail, and ending with the Queen had only one way up as the doubled-up soldiers were silent, and looked at poor Alice, who felt ready to sink into the teapot. 'At any rate he might answer questions.--How am I to get in?' asked Alice again, in a pleased tone. 'Pray don't trouble yourself to say it any longer than that,' said the Mock Turtle angrily: 'really you are very dull!' 'You ought to have any pepper in that soup!' Alice said to herself, 'I wonder if I've been changed for Mabel! I'll try and say "How doth the little--"' and she said this last remark that had fluttered down from the sky! Ugh, Serpent!' 'But I'm not used to read fairy-tales, I fancied that kind of thing never happened, and now here I am so VERY remarkable in that; nor did Alice think it so yet,' said Alice; 'I might as well go in at the thought that SOMEBODY ought to be managed? I suppose you'll be telling me next that you had been anxiously looking across the garden, and marked, with one eye; but to get through the neighbouring pool--she could hear him sighing as if he doesn't begin.' But she went on, looking anxiously about as much as serpents do, you know.' 'I DON'T know,' said Alice, whose thoughts were still running on the other was sitting on the bank--the birds with draggled feathers, the animals with their heads down! I am so VERY remarkable in that; nor did Alice think it was,' said the March Hare. The Hatter looked at the top of its mouth and yawned once or twice, and shook itself. Then it got down off the subjects on his knee, and looking anxiously about her. 'Oh, do let me hear the words:-- 'I speak severely to my jaw, Has lasted the rest of the game, feeling very glad she had never heard it before,' said Alice,) and round the neck of the e--e--evening, Beautiful, beautiful Soup!' CHAPTER XI. Who Stole the Tarts? The King laid his hand upon her face. 'Very,' said Alice: 'besides, that's not a mile high,' said Alice. 'Exactly so,' said the Duck: 'it's generally a frog or a serpent?' 'It matters a good deal worse off than before, as the question was evidently meant for her. 'Yes!' shouted Alice. 'Come on, then,' said the Gryphon, and all that,' said Alice. 'Come on, then!' roared the Queen, pointing to the jury, of course--"I GAVE HER ONE, THEY GAVE HIM TWO--" why, that must be growing small again.' She got up and say "Who am I to get into the wood. 'If it had a door leading right into a large one, but it said in a fight with another hedgehog, which seemed to her in such a wretched height to rest her chin upon Alice's shoulder, and it said in an agony of terror. 'Oh, there goes his PRECIOUS nose'; as an unusually large saucepan flew close by it, and they repeated their arguments to her, though, as they used to call him Tortoise, if he would not allow without knowing how old it was, even before she had but to her head, and she ran across the garden, where Alice could only see her. She is such a thing before, but she had never seen such a dreadful time.' So Alice got up in a very fine day!' said a sleepy voice behind her. 'Collar that Dormouse,' the Queen shrieked out..
"

**Comment by indpurvesh** [comment]
@cchoe1 reason being that is for the Product Filter Feature of the AvoRed E commerce.

For Example : 

Product Attributes has an options of: Size, Color and etc 
In that case Customer can filter the product based on Color and size on Category Page.

I hope it make sense

**Comment by cchoe1** [comment]
I'm not sure if that made any more sense to me

**Comment by indpurvesh** [comment]
<img width="1188" alt="screen shot 2018-05-20 at 11 52 07 am" src="https://user-images.githubusercontent.com/4218702/40274170-4537e9ca-5c24-11e8-9159-3afd04c1b7c0.png">

**Comment by indpurvesh** [comment]
Seems like i didn't get it what you mean by `giant story within the $products array `?

**Comment by cchoe1** [comment]
I used `print_r($products)` in CategoryViewController.php with a default installation.  I wanted to see what the variable was passing to the view so I did that and that huge story came up.

**Comment by indpurvesh** [comment]
Yes i get it. Rather then typing the Actual Product Description i am using an Faker to generate a giant description for Product Description. If you want you can change it in admin.

**Comment by cchoe1** [comment]
Ahh okay that makes sense.  Thanks
