### ISSUE TITLE
Retrieving current theme within module view

### ISSUE THREAD

**Issue by cchoe1** [avored/laravel-ecommerce#151]
Is there an easy way to resolve the current theme so that we can load the proper layouts?  I want to create a module that will pull the admin menu wireframe and then just inject content into the 'content' section.

From a quick glance, it seems the layouts are just duplicated within a module and then pulled from that copy.  So that means if we start loading a lot of modules, anytime we want to change the view, we would have to edit every copy of it.

**Comment by indpurvesh** [comment]
@cchoe1 If you want to create a new theme its very simple.

create a folder structure like below:

    - themes
      -  vendor_name
         - theme_name
           = assets
           = lang 
           = views
        - register.yaml (file)

register.yaml file content 

    identifier: vendor-theme
    name: YOUR THEME NAME
    asset_folder_name: assets
    lang_folder_name: lang             

One you have a folder and `register.yaml` file is there then in admin=>system=>theme

 click on activate theme. 

create a file inside a `themes/views/layouts/app.blade.php`

If you need more help please follow 

(https://laravel.com/docs/5.6/blade)[Laravel Blade Template]

I hope it helps

**Comment by cchoe1** [comment]
Sorry I didn't mean for creating themes.  I'm simply wanting to 'inherit' from the current theme.  I'm trying to create a module and I've already got it all connected together.  But when I go to the actual view, it doesn't have the admin navigation, the headers, or any of the HTML.  I am wondering if there is an easy way to 'namespace' the request for a view.  

In other words, I'd like an easy way to create a new module and tell it to pull the layouts from the current theme.  Rather than having to duplicate the theme, I'd rather 'extend' the main layout and then have my custom views inject into the 'content' section.

Thank you for the reply

**Comment by indpurvesh** [comment]
How to add AdminMenu:

Open your `Module.php` file open a `boot` method.

Let say you want to add a Submenu under CMS


    use AvoRed\Framework\AdminMenu\Facade as AdminMenuFacade;
    use AvoRed\Framework\AdminMenu\AdminMenu;
    $cmsMenu = AdminMenuFacade::get('cms');

      
        $myModuleMenu = new AdminMenu();
        $myModuleMenu->key('identifier')
            ->label('Menu Title')
            ->route('menu.route) 
            ->icon('menu-icon');

        $cmsMenu->subMenu('identifier', $myModuleMenu);


How to load an admin layout into your view file:

    @extends('avored-ecommerce::layouts.app')

    @section('content')
    <div class="container">
        Hello Admin Layout
    </div>
    @stop

**Comment by cchoe1** [comment]
Ah okay thanks, I was trying to hint the path but I think my cache was messing up and not showing the changes.  Thanks for verifying that though, it's working now.  Thanks!

**Comment by cchoe1** [comment]
In regards to the route path hint, what if someone wants to replace the admin theme with their own but still wants to use a module?  They'd have to change the namespace of their route for all the views of a module.  Or am I mistaken?

**Comment by indpurvesh** [comment]
I don't think i would allow to change the admin theme even in future.

**Comment by indpurvesh** [comment]
Yes you right if someone wants to change the admin theme completely they have to change the all the namespace into all the view files.

**Comment by cchoe1** [comment]
Oh okay sure that makes sense.  Thanks for all your time!

**Comment by indpurvesh** [comment]
@cchoe1 You welcome.

Yes . i do agree with that fact that right now Admin Theme is not the one of the best one but i think it will go better eventually. you know once themes gets nicer.

**Comment by cchoe1** [comment]
Oh I wasn't trying to imply that, I was just trying to plan for the future for my module.  I'm starting off with something small like an API integration for ShipEngine just so I can get a feel for Laravel package development/module development with this particular framework.

**Comment by indpurvesh** [comment]
@cchoe1 No  Don't be sorry its not you its me who think that my admin design is not great. Honestly i want to change the design but i think feature and code quality is more important then design so i will change the design but not my priority. Thanks for understanding.
