### ISSUE TITLE
error savin product HELP plz

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#152]
Error in Saving Product: Undefined variable: images

in ......\src\Http\Controllers\ProductController.php

    public function update(ProductRequest $request, ProductModel $product)
    {
    
        try {
            //$product = ProductModel::findorfail($id);
            $product->saveProduct($request->all());
        } catch (\Exception $e) {
            throw new \Exception('Error in Saving Product: '.$e->getMessage());
        }
 
        return redirect()->route('admin.product.index');
    }

**Comment by indpurvesh** [comment]
I have find the bug and have fixed it on my repository. I can't commit the code because i am in the middle of something and silly me haven't created another branch for my dev so if you replace the code by urself it should work for you.


Fix: open a file in `vendor/avored/framework/src/Models/Database/Product.php` find a method called `saveProductImages` it should be around line number 133.

Replace the code with

    /**
     * Save Product Images.
     *
     * @param array $$data
     * @return \AvoRed\Framework\Models\Database\Product $this
     */
    public function saveProductImages(array $data):self
    {
        if (isset($data['image']) && count($data['image']) > 0) {

            $exitingIds = $this->images()->get()->pluck('id')->toArray();
            // this below line has changed:  foreach ($images as $key => $data) {
            foreach ($data['image'] as $key => $data) {
                if (is_int($key)) {
                    if (($findKey = array_search($key, $exitingIds)) !== false) {
                        $productImage = ProductImage::findorfail($key);
                        $productImage->update($data);
                        unset($exitingIds[$findKey]);
                    }
                    continue;
                }
                ProductImage::create($data + ['product_id' => $this->id]);
            }
            if (count($exitingIds) > 0) {
                ProductImage::destroy($exitingIds);
            }

        }
        return $this;
    }

**Comment by aryby** [comment]
fixed,
thank you so much

**Comment by aryby** [comment]
same probleme in last version
the solution of change the function saveProductImages in vendor/avored/framework/src/Models/Database/Product.php
isn't work's right now

**Comment by aryby** [comment]
fixed i m edit this line in (vendor\avored\framework\src\Image\Localfile.php)
$this->$objectVarName = asset('storage/' . $sizeNamePath);
to $this->$objectVarName = asset( $sizeNamePath);
    /**
     * Pass Relative path for the file.
     *
     * @param null|string $relativePath
     */
    public function __construct($relativePath = null)
    {
        $this->relativePath = $relativePath;
        $this->url = asset($relativePath);

        $sizes = config('avored-framework.image.sizes');

        foreach ($sizes as $sizeName => $widthHeight) {
            $objectVarName = $sizeName . 'Url';

            $baseName = basename($relativePath);
            $sizeNamePath = str_replace($baseName, $sizeName . '-' . $baseName, $relativePath);

            $this->$objectVarName = asset($sizeNamePath);
        }
    }

**Comment by indpurvesh** [comment]
Reason being with those change is: Now i decided to store my Image and other media files into storage folder rather then public folder.  

To make it work in your case instead of changing the code i would do: 

    php artisan storage:link

This command create a symbolic link to your public/storage => storage/app/public which is where new images/media files gets stored. I hope it make sense.

**Comment by indpurvesh** [comment]
I need to check that extra "/". 

Why your images gets saved into public folder is because you have done installation using an old version. I think i have changed the publish folder into new version already. 

https://github.com/avored/dummy-data/blob/master/src/Module.php

checkout the `published` method

**Comment by aryby** [comment]
Yes that's it
i have
public function publishFiles() {
        $this->publishes([__DIR__.'/../assets' => public_path()], 'public');
    }

NB : but i have a last vesion

**Comment by aryby** [comment]
src="http://localhost:8000/storage//uploads/catalog/images/6/6/q/small-discount-1015446_1920.jpg"

i think in localfile.php

in public function __construct($relativePath = null)
    {
//
$this->$objectVarName = asset('storage/' . $sizeNamePath);


must be
$this->$objectVarName = asset('storage' . $sizeNamePath);

**Comment by indpurvesh** [comment]
I seen it but the bug is in path that gets stored in DB:

     $sizeNamePath "/PATH/FILENAME.jpg"; // which is wrong 

It should be : 

      $sizeNamePath "PATH/FILENAME.jpg";

**Comment by mikeyapina** [comment]
product.php is giving an error when i open the code begins around line 133 = the red error says - language features not compatible.

I am using PhP 7.2 - also what is significant is I cannot do the following:

1. when i pick an image to upload nothing happens other than teh item name is put into box but no image is presented or anyhting just name

2. the Save Product is gray so i can't pick it even though i have made other changes on teh product page



========== comnde in file with error marler ====
    public function saveProductImages(array $data):self
    {
        if (isset($data['image']) && count($data['image']) > 0) {
            $exitingIds = $this->images()->get()->pluck('id')->toArray();
            foreach ($data['image'] as $key => $data) {
                if (is_int($key)) {
                    if (($findKey = array_search($key, $exitingIds)) !== false) {
                        $productImage = ProductImage::findorfail($key);
                        $productImage->update($data);
                        unset($exitingIds[$findKey]);
                    }
                    continue;
                }
                ProductImage::create($data + ['product_id' => $this->id]);
            }
            if (count($exitingIds) > 0) {
                ProductImage::destroy($exitingIds);
            }
        }
        return $this;
    }
