### ISSUE TITLE
menu chiled

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#154]
when a create sub menu in admin panel
in navbar not work

**Comment by aryby** [comment]
error
"Class App\Http\ViewComposers\MenuInterface does not exist (View: C:...\themes\avored\default\views\home\index.blade.php)"

**Comment by aryby** [comment]
public function __construct(MenuInterface $repository)
        {
            $this->repository = $repository;
        }

**Comment by indpurvesh** [comment]
If you don't have the  repository yet in that case:



    use AvoRed\Ecommerce\Models\Database\Menu;

    public function compose(View $view)
    {
        $cart = (null === Session::get('cart')) ? 0 : count(Session::get('cart'));

        $menus = Menu::whereParentId(null)->orWhere('parent_id','=',0)->get();
        $metaTitle = Configuration::getConfiguration('general_site_title');
        $metaDescription = Configuration::getConfiguration('general_site_description');

        $view->with('menus', $menus)
            ->with('cart', $cart)
            ->with('metaTitle', $metaTitle)
            ->with('metaDescription', $metaDescription);
      }

**Comment by aryby** [comment]
partially fixed by public function compose(View $view)...

in version 2.3
same error
"Class App\Http\ViewComposers\MenuInterface does not exist (View: C:...\themes\avored\default\views\home\index.blade.php)"

**Comment by indpurvesh** [comment]
@aryby Yes you right on that particular commit i miss the file to commit.

open a file: `modules/avored/ecommerce/src/Provider.php` and put the below code:

    use AvoRed\Ecommerce\Models\Contracts\MenuInterface;
    use AvoRed\Ecommerce\Models\Repository\MenuRepository;

    /**
     * Register the Repository Instance.
     *
     * @return void
     */
    protected function registerModelContracts()
    {
        $this->app->bind(AdminUserInterface::class,AdminUserRepository::class);
        // New line below
        $this->app->bind(MenuInterface::class,MenuRepository::class);
    }

**Comment by aryby** [comment]
probleme
"Class AvoRed\Ecommerce\Models\Contracts\MenuInterface does not exist (View: C:\wamp64\www\laravel-ecommerce-2.3\themes\avored\default\views\home\index.blade.php)

**Comment by aryby** [comment]
do you have a code of class MenuInterface

**Comment by aryby** [comment]
in C:\...\modules\avored\ecommerce\src\Http\Controllers\DashboardController.php
public function index()
    {..
       $totalOrder = $this->repository->all()->count();

Call to undefined method AvoRed\Framework\Models\Repository\OrderRepository::all()

**Comment by indpurvesh** [comment]
to me seems like for some reason your code base is completely different then mine. with below url you will see all the code base fro this project:
https://github.com/avored

Order Repository code is inside a framework repository. below url

https://github.com/avored/framework

**Comment by aryby** [comment]
the error is fixed in last version 
by avored/frameowrk 1.5.1
thank you
