### ISSUE TITLE
the picture removal button does not work

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#156]
![capture](https://user-images.githubusercontent.com/37639238/41182534-a1c87aec-6b65-11e8-9218-9bb6d4b19236.PNG)

the removal button does not work

**Comment by indpurvesh** [comment]
Try this code into your repository:

`modules/avored/ecommerce/src/Http/Controllers/ProductController@deleteImage`:

    /**
     * upload image file and resized it.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function deleteImage(Request $request)
    {
        $path = $request->get('path');

        $path = 'uploads/catalog/images/e/0/v/1382542458778.jpeg';
        $fileName = pathinfo($path, PATHINFO_BASENAME);
        $relativeDir = pathinfo($path, PATHINFO_DIRNAME);

        // changed line:    $sizes = config('image.sizes');
        $sizes = config('avored-framework.image.sizes');
        foreach ($sizes as $sizeName => $widthHeight) {
            $imagePath = $relativeDir . DIRECTORY_SEPARATOR . $sizeName . '-' . $fileName;
            if (File::exists($imagePath)) {
                File::delete(storage_path('app/public/' . $imagePath));
            }
        }

        if (File::exists($path)) {
            File::delete(storage_path('app/public/' . $path));
        }
        return JsonResponse::create(['success' => true]);
    }

**Comment by aryby** [comment]
it's work thank u
