### ISSUE TITLE
Error in Order (Dashboard admin)

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#157]
whene i change status (http://localhost:8000/admin/order/2/change-status) and clik save
-->Undefined variable: id
 IN ...\laravel-ecommerce-master\modules\avored\ecommerce\src\Http\Controllers\OrderController.php
-->    
  /**
     * Change the Order Status
     * @param \AvoRed\Ecommerce\Models\Database\Order $order
     * 
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateStatus(Model $order, UpdateOrderStatusRequest $request)
    {
        $order = Model::find($id);

when i do  $order = Model::find($order->id);
i have the error

(http://localhost:8000/admin/order/2/update-status)

Process could not be started [The specified path was not found. 

NB : status change

**Comment by indpurvesh** [comment]
Fixed: Just remove or Uncomment a line `//$order = Model::find($id);`

I have fixed the issue on dev branch but replace the `modules/avored/ecommerce/src/Http/Controllers/OrderController@updateStatus` method with below :

    /**
     * Change the Order Status
     * @param \AvoRed\Ecommerce\Models\Database\Order $order
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateStatus(Model $order, UpdateOrderStatusRequest $request)
    {
        //$order = Model::find($id);
        $order->update($request->all());

        $userEmail = $order->user->email;
        $orderStatusTitle = $order->orderStatus->name;

        Mail::to($userEmail)->send(new UpdateOrderStatusMail($orderStatusTitle));

        return redirect()->route('admin.order.index');
    }

**Comment by aryby** [comment]
when i do that
and change status of order 

C:\Users\EL ARYBY\Desktop\pro\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php
        $this->in = &$this->stream;
        $this->out = &$this->stream;
    }
 
    /**
     * Opens a process for input/output.
     */
    private function establishProcessConnection()
    {
        $command = $this->params['command'];
        $descriptorSpec = array(
            0 => array('pipe', 'r'),
            1 => array('pipe', 'w'),
            2 => array('pipe', 'w'),
            );
        $pipes = array();
        $this->stream = proc_open($command, $descriptorSpec, $pipes);
        stream_set_blocking($pipes[2], 0);
        if ($err = stream_get_contents($pipes[2])) {
            throw new Swift_TransportException(
                'Process could not be started ['.$err.']'
                );
        }
        $this->in = &$pipes[0];
        $this->out = &$pipes[1];
    }
 
    private function getReadConnectionDescription()
    {
        switch ($this->params['type']) {
            case self::TYPE_PROCESS:
                return 'Process '.$this->params['command'];
                break;
 
            case self::TYPE_SOCKET:

the error is
Swift_TransportException
Process could not be started [The specified path was not found.\r\n
]

**Comment by indpurvesh** [comment]
It the same reason you are not receiving an Email while place an order and create an account.

 As a development process you can create an account on Mailtrap its free and good for dev purpose.

https://mailtrap.io/

How to setup in Laravel 

https://laracasts.com/discuss/channels/general-discussion/mailtrap-laravel

**Comment by aryby** [comment]
that's it
thank u
