### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by mahdi7abash** [avored/laravel-ecommerce#159]
**Trying to log into admin side  below error appear**
ErrorException (E_WARNING)
Illegal offset type in isset or empty

**Screenshots**
![illegal offset](https://user-images.githubusercontent.com/14835811/41217985-483e3526-6d62-11e8-994d-76394a0c2d56.png)

**Desktop /information:**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Tried to install a fresh update but its full of errors 
such Trying to get property 'configuration_value' of non-object under admin=> configuration

**Comment by indpurvesh** [comment]
Sorry i did a fresh install of AvoRed in separate folder of mine. For some reason i can't replicate your bug. On my copy. 
Is there anything more you can give me. Seems like you seeing the bug of some kind of auth guard related based on the screenshot. (Possibly when you click on a Login button of Admin?)?

**Comment by mahdi7abash** [comment]
@indpurvesh please can you give me the steps to do correct installation since the documentation page in your website not showing any thing .. 
and after fresh installation i will give you my feedback
thanks

**Comment by indpurvesh** [comment]
Below is the step i have done it on my Computer

Go to Directory you like to install AvoRed E commerce:

Execute a composer commanad:
    composer create-project avored/laravel-ecommerce FOLDER_NAME

then execute Installation command: 

    cd FOLDER_NAME
    php artisan avored:install

then execute AvoRed Admin Make (New Command):

     php artisan avored:admin:make


I hope it helps

**Comment by indpurvesh** [comment]
just open a RoleRepository file which you can find at: `modules/avored/ecommerce/src/Models/Repository/RoleRepository.php` and add a below code on top of your file:


    use AvoRed\Ecommerce\Models\Database\Role;

**Comment by rylxes** [comment]
i am still having this issue with a fresh installation
