### ISSUE TITLE
error php artisan route:list

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#160]
$ php artisan route:list

   Illuminate\Contracts\Container\BindingResolutionException  : Target [AvoRed\Ecommerce\Models\Contracts\PageInterface] is not instantiable while building [AvoRed\Ecommerce\Http\Controllers\P
ageController].

  at C:\Users\EL ARYBY\Desktop\pro\vendor\laravel\framework\src\Illuminate\Container\Container.php: 933
  929:         } else {
  930:             $message = "Target [$concrete] is not instantiable.";
  931:         }
  932:
  933:         throw new BindingResolutionException($message);
  934:     }
  935:
  936:     /**
  937:      * Throw an exception for an unresolvable primitive.
  938:      *

  Exception trace:

  1   Illuminate\Container\Container::notInstantiable("AvoRed\Ecommerce\Models\Contracts\PageInterface")
      C:\...\vendor\laravel\framework\src\Illuminate\Container\Container.php : 773

  2   Illuminate\Container\Container::build("AvoRed\Ecommerce\Models\Contracts\PageInterface")
      C:...pro\vendor\laravel\framework\src\Illuminate\Container\Container.php : 646

  Please use the argument -v to see more details.

**Comment by indpurvesh** [comment]
If you just do a `composer update` i hope it should fixed the bug for you.

**Comment by indpurvesh** [comment]
After `composer update` it should fixed your admin product edit page vuejs bug too

**Comment by aryby** [comment]
for bug vuejs not work this update
just i fix bay this
npm install
npm run avored:admin

**Comment by aryby** [comment]
and also http://localhost:8000/admin/page not fixed

C:\Users\EL ARYBY\Desktop\pro\vendor\laravel\framework\src\Illuminate\Container\Container.php
 
    /**
     * Throw an exception that the concrete is not instantiable.
     *
     * @param  string  $concrete
     * @return void
     *
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    protected function notInstantiable($concrete)
    {
        if (! empty($this->buildStack)) {
            $previous = implode(', ', $this->buildStack);
 
            $message = "Target [$concrete] is not instantiable while building [$previous].";
        } else {
            $message = "Target [$concrete] is not instantiable.";
        }
 
        throw new BindingResolutionException($message);
    }
//-------------------------------------------------------------------------------------------------------
Illuminate \ Contracts \ Container \ BindingResolutionException
Target [AvoRed\Ecommerce\Models\Contracts\PageInterface] is not instantiable while building [AvoRed\Ecommerce\Http\Controllers\PageController].

msg error 
Target [AvoRed\Ecommerce\Models\Contracts\PageInterface] is not instantiable while building [AvoRed\Ecommerce\Http\Controllers\PageController].

**Comment by aryby** [comment]
yes it's fixed
