### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#164]
in page for example : http://localhost:8000/category/pc

when I click on a product (image) to have more details

when I click on a product (image) to have more details

it gives me an error -> 
\avored\vendor\laravel\framework\src\Illuminate\Container\Container.php

Target [AvoRed\Framework\Models\Contracts\ProductDownloadableUrlInterface] is not instantiable while building [App\Http\Controllers\ProductViewController].

**Comment by indpurvesh** [comment]
When you did download this code? i just commit this code today?

try doing:

    composer update

I hope it fixed your problem.

**Comment by aryby** [comment]
yes i work for the last commit
