### ISSUE TITLE
Suggestion and bug in avord.com

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#165]
hello 
Just a suggestion 
if someone add to cart a product
in the CART menu you can add a badge( <span class="badge badge-light">) with the numbers of products

when i want to tak a message in contact Page in your site avored.com
he gives me an error
Swift_TransportException (530)
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "
-------------------swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php

**Comment by indpurvesh** [comment]
just add below code into nav-tree.blade.php

`themes/avored/default/views/layouts/menu-tree.blade.php`

    @if($menu->route == "cart.view")
            <a class="nav-link" href="{{ $url }}">
                {{ $menu->name }} <span class="badge badge-primary">{{ Cart::count() }}</span>
            </a>
    @else

            <a class="nav-link" href="{{ $url }}">
                {{ $menu->name }}
            </a>
    @endif

**Comment by aryby** [comment]
i just doin this in 
loop foreach
@if($menu->route == "cart.view")
                    <a class="nav-link" href="{{ $url }}">
                        <span class="badge badge-primary">{{ Cart::count() }}</span>
                    </a>
                @endif

NB : i have a Cart in last item in NavBar
