### ISSUE TITLE
Error Banner image in admin Dashboard

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#168]
hello
Now I am working on version 2.5
when I make a new banner in admin Dashboard 
the image can not be displayed properly
when I do inspect I find : http://localhost:8000/uploads/cms/images/b/r/0/1.jpg

and in the folder the image is save as : j893xGICaC6lb0YmMLUnssY33Mx9GiZeFEB2IcvT.jpeg

NB : error existe in producte image also
i m  doing  the storage:link

**Comment by indpurvesh** [comment]
Image Path bug has been fixed in Banner Module with Repository Pattern and route model binding too. 

How to fixed change the Banner version to 1.7 inside a `composer.json`


    "avored/banner": "~1.7",

Run the Command:

    composer update
