### ISSUE TITLE
Table 'shopm.avored_order_histories' doesn't exist 

### ISSUE THREAD

**Issue by pastushenkofx** [avored/laravel-ecommerce#172]
ubuntu@ip-172-31-42-201:/var/www/rshop$ php artisan avored:install -v

 Do you want to Install Dummy Data? (y/n) [yes]:
 > y

Application key [base64:d53cXLve/r4Y2gwTdrQ1aOZcVdUJOP3gDvRMwIRK0MY=] set successfully.
Migration table created successfully.

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopm.avored_order_histories' doesn't exist (SQL: alter table `avored_order_histories` add `id` int unsigned not null auto_increment primary key, add `order_id` int unsigned null, add `order_status_id` int unsigned null, add `created_at` timestamp null, add `updated_at` timestamp null)

  at /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Connection.php: 664
  660:         // If an exception occurs when attempting to run a query, we'll format the error
  661:         // message to include the bindings with SQL, which will make this exception a
  662:         // lot more helpful to the developer instead of just the database's errors.
  663:         catch (Exception $e) {
  664:             throw new QueryException(
  665:                 $query, $this->prepareBindings($bindings), $e
  666:             );
  667:         }
  668: 
  669:         return $result;

  Exception trace:

  1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopm.avored_order_histories' doesn't exist")
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 458

  2   PDOStatement::execute()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 458

  3   Illuminate\Database\Connection::Illuminate\Database\{closure}("alter table `avored_order_histories` add `id` int unsigned not null auto_increment primary key, add `order_id` int unsigned null, add `order_status_id` int unsigned null, add `created_at` timestamp null, add `updated_at` timestamp null", [])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 657

  4   Illuminate\Database\Connection::runQueryCallback("alter table `avored_order_histories` add `id` int unsigned not null auto_increment primary key, add `order_id` int unsigned null, add `order_status_id` int unsigned null, add `created_at` timestamp null, add `updated_at` timestamp null", [], Object(Closure))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 624

  5   Illuminate\Database\Connection::run("alter table `avored_order_histories` add `id` int unsigned not null auto_increment primary key, add `order_id` int unsigned null, add `order_status_id` int unsigned null, add `created_at` timestamp null, add `updated_at` timestamp null", [], Object(Closure))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 459

  6   Illuminate\Database\Connection::statement("alter table `avored_order_histories` add `id` int unsigned not null auto_increment primary key, add `order_id` int unsigned null, add `order_status_id` int unsigned null, add `created_at` timestamp null, add `updated_at` timestamp null")
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php : 88

  7   Illuminate\Database\Schema\Blueprint::build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php : 264

  8   Illuminate\Database\Schema\Builder::build(Object(Illuminate\Database\Schema\Blueprint))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php : 149

  9   Illuminate\Database\Schema\Builder::table("order_histories", Object(Closure))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php : 221

  10  Illuminate\Support\Facades\Facade::__callStatic("table")
      /var/www/rshop/vendor/avored/framework/database/migrations/2017_03_29_000000_avored_framework_schema.php : 132

  11  AvoredFrameworkSchema::up()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 359

  12  Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 366

  13  Illuminate\Database\Migrations\Migrator::runMigration(Object(AvoredFrameworkSchema), "up")
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 177

  14  Illuminate\Database\Migrations\Migrator::runUp("/var/www/rshop/vendor/avored/framework/src/../database/migrations/2017_03_29_000000_avored_framework_schema.php")
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 146

  15  Illuminate\Database\Migrations\Migrator::runPending([])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 95

  16  Illuminate\Database\Migrations\Migrator::run([])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php : 70

  17  Illuminate\Database\Console\Migrations\MigrateCommand::handle()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  18  call_user_func_array([])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  19  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 87

  20  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 31

  21  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/Container.php : 564

  22  Illuminate\Container\Container::call()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Console/Command.php : 184

  23  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      /var/www/rshop/vendor/symfony/console/Command/Command.php : 251

  24  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Console/Command.php : 171

  25  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Console/Command.php : 199

  26  Illuminate\Console\Command::call("migrate")
      /var/www/rshop/vendor/avored/framework/src/Support/Console/InstallCommand.php : 58

  27  AvoRed\Framework\Support\Console\InstallCommand::handle()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  28  call_user_func_array([])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  29  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 87

  30  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 31

  31  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Container/Container.php : 564

  32  Illuminate\Container\Container::call()
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Console/Command.php : 184

  33  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/rshop/vendor/symfony/console/Command/Command.php : 251

  34  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Console/Command.php : 171

  35  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/rshop/vendor/symfony/console/Application.php : 886

  36  Symfony\Component\Console\Application::doRunCommand(Object(AvoRed\Framework\Support\Console\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/rshop/vendor/symfony/console/Application.php : 262

  37  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/rshop/vendor/symfony/console/Application.php : 145

  38  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Console/Application.php : 89

  39  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/rshop/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php : 122

  40  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/rshop/artisan : 35

**Comment by indpurvesh** [comment]
Simply just do composer update it should fixed your problem.

    composer update

**Comment by aryby** [comment]
i  do composer update
php artisan migrate

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 La table 'avored_categories' existe déjà (SQL: create table `avored_categories` (`id` int unsi
gned not null auto_increment primary key, `parent_id` int null, `name` varchar(255) not null, `slug` varchar(255) not null, `meta_title` varchar(255) null, `meta_description` varchar(255) null
, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)B)

  at C:\Users\EL ARYBY\Desktop\laravel-ecommerce-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php: 664
  660:         // If an exception occurs when attempting to run a query, we'll format the error
  661:         // message to include the bindings with SQL, which will make this exception a
  662:         // lot more helpful to the developer instead of just the database's errors.
  663:         catch (Exception $e) {
  664:             throw new QueryException(
  665:                 $query, $this->prepareBindings($bindings), $e
  666:             );
  667:         }
  668:
  669:         return $result;

  Exception trace:

  1   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 La table 'avored_categories' existe déjà")")
      C:\Users\EL ARYBY\Desktop\laravel-ecommerce-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 458

  2   PDOStatement::execute()
      C:\Users\EL ARYBY\Desktop\laravel-ecommerce-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 458

**Comment by indpurvesh** [comment]
@aryby  You can't use `php artisan migrate` because I am not supporting any kind of version upgrade at this stage because DB is changing so much as I am still working on many features.  I hope it makes sense. I would guess in your case you might be missing an `order_histories` table so I would suggest you can do it simply by adding Schema create a table into the controller for once then remove it.

Open a HomeController File: `App\Http\Controllers\HomeController.php`

      public function index() {
     \Illuminate\Support\Facades\Schema::create('order_histories', function (\Illuminate\Database\Schema\Blueprint $table) {
            $table->increments('id');

            $table->integer('order_id')->unsigned()->nullable()->default(null);
            $table->integer('order_status_id')->unsigned()->nullable()->default(null);

            $table->timestamps();

            $table->foreign('order_status_id')->references('id')->on('order_statuses');
            $table->foreign('order_id')->references('id')->on('orders');
        });
       // LEAVE REST OF THE CODE HERE..... Just visit home page once which would create a table once table gets created into DB then remove the code...
       // Obviosly this is not an ideal way of doing it but still it works:

       }
