### ISSUE TITLE
bug in products (Admin area)

### ISSUE THREAD

**Issue by pastushenkofx** [avored/laravel-ecommerce#179]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Declaration of AvoRed\Framework\Models\Repository\ProductDownloadableUrlRepository::create(array $data) must be compatible with AvoRed\Framework\Models\Contracts\ProductDownloadableUrlInterface::create($data)

**Comment by pastushenkofx** [comment]
resolt...
in vendor/avored/framework/src/Models/Contracts/ProductDownloadableUrlInterface.php
non correct: public function create($data);
correct: public function create(array $data);

**Comment by indpurvesh** [comment]
@pastushenkofx you are right.

Bug has been fixed in dev branch. 

Thanks
