### ISSUE TITLE
error total in Shopping Cart

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#181]
![chekoutavo](https://user-images.githubusercontent.com/37639238/43040245-dbe663cc-8d36-11e8-9dcd-c1947fed9f09.PNG)

Menu child in this version not work (fixed in [https://github.com/avored/laravel-ecommerce/issues/154](url) )

**Comment by indpurvesh** [comment]
Fixed to Check:
Please update this two file.

 -  themes/avored/default/views/cart/view.blade.php
 - themes/avored/default/views/checkout/cards/shopping-cart.blade.php

**Comment by aryby** [comment]
whene i update product in http://localhost:8000/cart/view
 card not updated
 and the error chek
![anerror](https://user-images.githubusercontent.com/37639238/43090134-73d7b060-8e9e-11e8-9e11-9cf21a6c019d.PNG)

i well have 
![wellhave](https://user-images.githubusercontent.com/37639238/43090245-c0fd6b6e-8e9e-11e8-97c8-a0c6d0cad263.PNG)

**Comment by indpurvesh** [comment]
I am getting the right amount in both cart and checkout page.

You want to do 

    composer update

**Comment by aryby** [comment]
sorry but there is no place to put an image on the editor of www.avored.com

can you fixe this thing please [https://www.avored.com/discussion/error-category-in-navbar-total-shiping
](url)
