### ISSUE TITLE
getCategoryProductWithFilter does not exist

### ISSUE THREAD

**Issue by Pasteo2018** [avored/laravel-ecommerce#182]
Hi,
from the index page, when I click on Category Product, redirect on page that return this error:

BadMethodCallException
Method Illuminate\Database\Query\Builder::getCategoryProductWithFilter does not exist.

Thanks for feedback

**Comment by indpurvesh** [comment]
if you open a file and replace a code:  `app/Http/Controllers/CategoryViewController.php` 


     /**
      *
      * 
      * @param Request $request
      * @param $slug
      * @return \Illuminate\Http\Response
      *
      */
    public function view(Request $request, $slug)
    {
        $productsOnCategoryPage = 9;
        $category = $this->repository->findByKey($slug);
        $catProducts = $this->repository->getCategoryProductWithFilter($category->id, $request->except(['page']));
        $products = $this->repository->paginateProducts($catProducts, $productsOnCategoryPage);
        return view('category.view')
            ->with('category', $category)
            ->with('params', $request->all())
            ->with('products', $products);
    }

**Comment by indpurvesh** [comment]
This bug has been fixed in latest release. @Pasteo2018  thanks for raising the bug.
