### ISSUE TITLE
Duplicate toolbar when editing a product

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#187]
**Describe the bug**
When you try to edit a product you get a toolbar menu on the top left that is shown twice.

**To Reproduce**
1. Go to the admin interface and click on **Shop**.
2. Choose any product and click on **Edit**.
3. look at the top left
**Screenshots**
![producteditknipsel](https://user-images.githubusercontent.com/1594411/44007282-a47d697c-9e92-11e8-9298-33507fb44aed.PNG)

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 6.1.0.2

**Comment by indpurvesh** [comment]
@ghermans thanks for raising the issue. 

Fixed has been committed in Dev branch commit  # 6ca2cc7

Soon I will merge into a master branch.
