### ISSUE TITLE
Wrong currency displayed

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#191]
**Describe the bug**
When you select a different currency at the frontend top menu, prices are still displayed in $.

**Screenshots**
![currencyknipsel](https://user-images.githubusercontent.com/1594411/44039729-f64e1eb8-9f19-11e8-8ffc-0f32fb540737.PNG)

![cartknipsel](https://user-images.githubusercontent.com/1594411/44039827-406e7a1a-9f1a-11e8-907e-c800e9e80e89.PNG)

**Comment by indpurvesh** [comment]
i will add this bug into my list. thanks again.
