### ISSUE TITLE
Typo in widget total-user

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#196]
**Describe the bug**
The widget title displays **Total User** it actually should be **Total Customers**

**Screenshots**
The screenshot is taken from the **dev** branch but issue is also visible in the **master** branch.    

![widgetsknipsel](https://user-images.githubusercontent.com/1594411/44131817-bcab76aa-a055-11e8-8241-0dfccdafa444.PNG)

**Comment by indpurvesh** [comment]
Your query about the rename:=> Users => Customer 
I am thinking of adding an Alias configuration where they can put a What they want to call it. Is it 
 - `Add to Cart` or `Add to Bag` 
 - `User` => `Customer`

 I hope it make sense or another idea is to change it into a translation file?
What is your opinion?

**Comment by ghermans** [comment]
I would suggest to name it **customers** by default as that would be a logic name for it.
I also forgot that there should be a **Customers group** page. 
a customer group could be used to define for example
- The customer(user) as Residential/Small Business/ Enterprise.
- Custom discount price.
- Custom tax rate

This is just a idea of course but again i guess this would benefit the user experience.

**Comment by indpurvesh** [comment]
All three options are in my todo list already.
