### ISSUE TITLE
Optimize module management

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#201]
**Describe the solution you'd like**
The current method only allows admins to enable or disable a module, this is great and looks enough for developers.   
But we could make this page more useful for end-users who are not that experienced with composer / coding etc by making it simple to find and install new extensions (modules) similar to opencart / magento.    

#### Avored MarketPlace
I would suggest to add a "Marketplace section" on the AvoRed website where developers can publish there modules/themes.

This section would save the developers project data for example
- module_name
- module_repo
- ..

After that we could load the project data into the module page and use it to **install**, **enable**, **disable** the modules / themes.

**Comment by ghermans** [comment]
Rome wasn't build one day too so no problem ;) i'm just shooting idea's to the project.

**Comment by indpurvesh** [comment]
Obviously, I know it. I do appreciate what you are doing it too. once again thanks for all.
