### ISSUE TITLE
Product data is not being saved

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#212]
**Describe the bug**
When updating a product the category isn't saved.

**To Reproduce**
1. Go to **Shop**
2. Click on **Categories**
3. Click **edit** on a random product.
4. Change the category and see the result.

**Screenshots**
Edit screen
![editproductknipsel](https://user-images.githubusercontent.com/1594411/44623170-679bf600-a8c8-11e8-8013-e3943d81b2a7.PNG)
Selecting the category.
![addcatknipsel](https://user-images.githubusercontent.com/1594411/44623172-6e2a6d80-a8c8-11e8-878c-c08b63444069.PNG)

After i pressed Save Product i checked the shop
![noproductsknipsel](https://user-images.githubusercontent.com/1594411/44623176-88644b80-a8c8-11e8-9841-3939a48accab.PNG)

**Comment by indpurvesh** [comment]
@ghermans  I did try to replicate the bug. But its working fine for me.

**Comment by ghermans** [comment]
i will verify it again tonight

**Comment by juanmanavarro** [comment]
I'm having the same issue

**Comment by indpurvesh** [comment]
@juanmanavarro 

are you having an issue of product is being save in backend but not displaying in frontend?

**Comment by juanmanavarro** [comment]
@indpurvesh it's working now. I'm sorry
