### ISSUE TITLE
Error in "Create product" 

### ISSUE THREAD

**Issue by bkerberos** [avored/laravel-ecommerce#216]
The error occurs when uploading an image for the product

![image](https://user-images.githubusercontent.com/30532126/45504007-40f61000-b74e-11e8-850d-c63d48d6b3f6.png)

After recording I get the following

![image](https://user-images.githubusercontent.com/30532126/45504025-4ce1d200-b74e-11e8-9416-d9a7852f86c6.png)

The path in database

![image](https://user-images.githubusercontent.com/30532126/45504081-7bf84380-b74e-11e8-87ad-04cf1893bfa9.png)

Help !!

**Comment by ghermans** [comment]
Do you see the file in your folder?

**Comment by bkerberos** [comment]
If the files exist, It seems that the storage folder is created twice.

![image](https://user-images.githubusercontent.com/30532126/45513481-6859d680-b768-11e8-8968-a61644e8205a.png)


When uploading a new image either in products or banner, double route storage / storage is created

**Comment by indpurvesh** [comment]
I think In side image manager there is an upload method need to do str_ replace storage is a symlink for public folder

**Comment by bkerberos** [comment]
When you save a product, banner and profile picture, you create a double "storage / storage" route when you show it, I do not know how you could solve it.

**Comment by indpurvesh** [comment]
@bkerberos & @ghermans i have fixed the bug in dev branch. But soon i am thinking of rewrite `ImageManager`completely soon so i hope then i will add few more feature and few more unit test to make sure this won't occur again.
