### ISSUE TITLE
PlaceOrder Button is not working

### ISSUE THREAD

**Issue by Git-akash** [avored/laravel-ecommerce#230]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ghermans** [comment]
We can only guess what is wrong since you didn't fill in the issue template.
Have you configured the shipping and payment settings in the backend before trying to place the order in the frontend?

**Comment by Git-akash** [comment]
Thank you it Works!!
