### ISSUE TITLE
Add Unit Test and Refactor Code Base where it looks messy

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#238]

**Comment by nbrabant** [comment]
I'll see what i can do ;)

**Comment by dangenendt** [comment]
@nbrabant 
i started testing the CartController. This is nearly done. Perhabs you can start with another class? Thx man:man_dancing:

**Comment by indpurvesh** [comment]
@nbrabant @dangenendt Thanks

**Comment by nbrabant** [comment]
I'll start to test the OrderController

**Comment by nbrabant** [comment]
Hello. 
Hum... After trying to use mocking requests to test the OrderController, i have fail and actually i'm blocked on understanding the methods to use... (i'am junior in unit tests)
So, is here someone how help me to understand what i have missed? thanks

**Comment by indpurvesh** [comment]
usually, you don't mock the controller. If you still share some code would be easy to give you some suggestion.

If you follow laravel unit test docs they make it a unit test for the app is a lot easier.
https://laravel.com/docs/5.7/http-tests
you don't have to mock almost anything.

**Comment by dangenendt** [comment]
@nbrabant 
Have a look into the CartControllerTest i made (now in master).
I think then you will see how things work. If not, don't hesitate to ask.

**Comment by nbrabant** [comment]
Hello,
@dangenendt , i take a look on the CartControllerTest. For some mocking, i understand how it works, but i don't understand how i can define arguments in my mocked request
I've created a branch with the test in my fork, if someone can take a look an review to improve the test, i will be grateful
