### ISSUE TITLE
Product with Variation canAddToCart function doesn't work properly

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#246]
If Attribute Price is more then default price then Tax gets Calculated based on default price instead of the variable product price.

**Comment by narendravardi** [comment]
@ghermans, can i pick this up ?

**Comment by ghermans** [comment]
@narendravardi  sure, can you send a pull requests to the dev branch when you are done?

**Comment by indpurvesh** [comment]
If we have a Product with Attribute in that case when we call 

canAddToCart method check the parent product qty not the variation product qty.
So below code needs to use `$attribute`


     public function canAddToCart($slug, $qty, $attribute = [])
     {
         $cartProducts = $this->getSession();
         $cartProduct = $cartProducts->get($slug);
         $cartQty = $cartProduct ? $cartProduct->qty() : 0;
 
        $checkQty = $qty + $cartQty;
         $product = Product::whereSlug($slug)->first();
 
        $productQty = $product->qty;
         if ($productQty >= $checkQty) {
             return true;
         }
 
         return false;
     }

**Comment by ghermans** [comment]
@narendravardi any progress on this?

**Comment by indpurvesh** [comment]
@ghermans When I replicate this bug at that time  I did find some other product attribute related bug too, which I have fixed it. I think these bug should be fixed.

**Comment by ghermans** [comment]
Closing this issue as it should be fixed, please reopen it in case you still experience this issue.
