### ISSUE TITLE
Cart Manager should  return price formatted

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#254]
Adde a feature inside a Cart Manager. 

It should return formatted price if argument is passed e.g

    Cart::total($formatted = true); //It should return $4,500.00  and make sure $ is not hard coded and use Site Currency Symbol.

**Comment by phase06** [comment]
Hi @indpurvesh , I can look into this.

**Comment by indpurvesh** [comment]
@phase06 sure go ahead and make sure you do PR on dev branch.

If you need any help please comment.

For the currency symbol, you can use

    Session::get('currency_code')

**Comment by phase06** [comment]
okay thanks :+1:

**Comment by indpurvesh** [comment]
Yes you make changes and n that file and do a pull request on dev branch
