### ISSUE TITLE
avored:install - en_US locales are missing

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#261]
**To Reproduce**
1. enter `artisan avored:install`
2. See error

**Screenshots**
![installknipsel](https://user-images.githubusercontent.com/1594411/46772808-2df94000-ccfa-11e8-9d68-af25db7fed7c.PNG)

**Comment by indpurvesh** [comment]
i am going to remove locale check completely.

temp fix: 
Open a file
`config/self-diagnosis.php`

then comment out below code:

         //\BeyondCode\SelfDiagnosis\Checks\LocalesAreInstalled::class => [
         //   'required_locales' => [
         //       'en_US'
         //   ],
        //],
