### ISSUE TITLE
Laravel 5.7 Bug List

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#268]
I have upgrade laravel framework to 5.7

If you find any bug regarding laravel5.7 upgrade please comment it here. I try to fix most as a hotfix.

**Comment by bonucci** [comment]
Hello, i installed avored, and i created a new currency (euro), everything is fine, but in the frontend navigating to product detatils give me a error:

"Undefined variable: currencySymbol"

**Comment by indpurvesh** [comment]
@bonucci I will take a look at this bug asap. thanks

**Comment by indpurvesh** [comment]
I never had any issue regarding the upgrade so closing it.
