### ISSUE TITLE
error in banner

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#269]
when i wanna create a new banner image
![avored](https://user-images.githubusercontent.com/37639238/46952088-c9374000-d081-11e8-95e2-6cfc888db607.PNG)

**Comment by indpurvesh** [comment]
It is fixed in the dev branch.

in BannerController.php replace the 
 ~~use AvoRed\Framework\Image\Facade as Image;~~


    use AvoRed\Framework\Image\Facades\Image;

**Comment by aryby** [comment]
whene i do that i have an other error like this : 
![error2](https://user-images.githubusercontent.com/37639238/46978992-3c63a500-d0c8-11e8-92f0-8f2ed81e12ad.PNG)
