### ISSUE TITLE
Sku Product Variations

### ISSUE THREAD

**Issue by bonucci** [avored/laravel-ecommerce#275]
When creating a variable product, example a product with different colors, each product/color should have is own Sku.
Very important feature

**Comment by indpurvesh** [comment]
Actually yes variable product all has separate sku that gets generated automatically on creation but then you can edit and change it if you want.

**Comment by bonucci** [comment]
The steps. Let me check and then i can suggest a more user friendlly

**Comment by indpurvesh** [comment]
I have seen you should be able to change the sku in your existing app too. let me know if you not sure about the steps to do it.
