### ISSUE TITLE
Catalog  Properties

### ISSUE THREAD

**Issue by bonucci** [avored/laravel-ecommerce#276]
In Catalog > Properties there is some big bugs, for example this one:

```
private function _saveDropdownOptions($property, $request)
    {
        if (null !== $request->get('dropdown-options')) {
            $property->propertyDropdownOptions()->delete();

            foreach ($request->get('dropdown-options') as $key => $val) {
                if ($key == '__RANDOM_STRING__') {
                    continue;
                }

                $property->propertyDropdownOptions()->create($val);
            }
        }
    }
```

When you trigger "_saveDropdownOptions" instead of updating the values your deleting and creating them again. But this will mess the products properties values, since your IDs will be different...

**Comment by indpurvesh** [comment]
I agree. 

I did that delete and then insert to make few less query but you right it will delete all the existing product property. I have to fix it soon
