### ISSUE TITLE
Add Socialite support

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#278]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
In addition to typical, form based authentication, Laravel also provides a simple, convenient way to authenticate with OAuth providers using Laravel Socialite. Socialite currently supports authentication with Facebook, Twitter, LinkedIn, Google, GitHub and Bitbucket.

**Additional context**
Source https://laravel.com/docs/5.7/socialite

**Comment by indpurvesh** [comment]
@ghermans its in dev branch but still have to do a test with actual url because specially goole and facebook won't allow to test on local url.

**Comment by ghermans** [comment]
Nice, also can't we use a subdomain for example https://testing.avored.com to run a demo version of the dev branch?

**Comment by indpurvesh** [comment]
Thanks the plan. I am thinking of setting up dev branch on https://dev.avored.com
