### ISSUE TITLE
Change theme

### ISSUE THREAD

**Issue by bkerberos** [avored/laravel-ecommerce#280]
Hello, I would like to know where we could get themes to install and win, in any case how we could build a theme to match the avored classes in bootstrap.

**Comment by indpurvesh** [comment]
Below are the steps you can follow:

Execute Artisan command:

    php artisan avored:theme:make vendor_name theme_name

If you want you can copy and paste `js,css,images` folder and view file you copy and paste based on which one you want to override it. Let say i want to override login page then you only `themes/avored/default/views/auth/login.blade.php` to `themes/vendor_name/theme_name/views/auth/login.blade.php`

You can simply change the `webpack.mix.js` path to a newly created themes:


     mix.config.fileLoaderDirs.fonts     = "vendor/theme-identifier-goes-here/fonts";
     mix.config.fileLoaderDirs.images    = "vendor/theme-identifier-goes-here/images";

     mix.copy('themes/vendor_name/theme_name/assets/images', 'public/vendor/theme-identifier-goes-here/images');
     mix.sass('themes/vendor_name/theme_name/assets/sass/app.scss', 'vendor/avored-default/css');
     mix.js('themes/vendor_name/theme_name/assets/js/app.js', 'vendor/theme-identifier-goes-here/js');


You can find the `theme-identifier` from `themes/vendor_name/theme_name/register.yml` 

Once this done you can login to admin panel and go to

System => Themes => Click Activate

Done

**Comment by ghermans** [comment]
Closing this since @indpurvesh answered the question.
