### ISSUE TITLE
Product Variation Cart

### ISSUE THREAD

**Issue by ludioao** [avored/laravel-ecommerce#283]
E.g.
I can't have a T-Shirt with Size M and color Black? Its the same product, but Avored consider 2 distinct product. 

How to deal with this?

Regards

**Comment by indpurvesh** [comment]
Ideally yes it is two different product and that's the only way to manage different qty, price and almost anything by having two separate product or in other words: One parent and rest child products.

Sorry but i still don't understand your question? What do you want to achieve?

**Comment by ludioao** [comment]
Sorry, friend. 

I've seen how it works.
