### ISSUE TITLE
Product Variation on Cart.

### ISSUE THREAD

**Issue by ludioao** [avored/laravel-ecommerce#285]
Hello, friend.

When I try to add a product without stock, the framework add normally without problems.

Could you block variation products without stock? 

Tks

**Comment by indpurvesh** [comment]
You mean on backend your product variation qty is 0 and it allow you to add to cart?

**Comment by ludioao** [comment]
Yes! 

btw, also I need to get info to freight calculate such as width, height, weight... how can I get this info? I didnt find anyway

**Comment by indpurvesh** [comment]
You can find all the freight calculation fields on backend side in the product edit page.

Yesterday when I was doing a testing with product variation I have noticed some other bug too and to fixed those bug I have to do some database change as well. I will work on it and most likely do a release in next sprint.

**Comment by ludioao** [comment]
Thanks @indpurvesh . I'll wait the next release. Now I'm working on a e-commerce website and it's the first time I use AvoRed as a e-commerce platform.
