### ISSUE TITLE
Pickup From Store should be displayed at shipping methods

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#286]
**Describe the bug**
Currently the option **Pickup From Store** is displayed as a payment method.
this should be a shipping method.
Additional the payment method should be 'Pay at pickup' or something similar.

**Screenshots**
![shipping](https://user-images.githubusercontent.com/1594411/49534892-08844f00-f8c3-11e8-9d4c-4b399eb2d865.PNG)

**Comment by ghermans** [comment]
updated description with additional info.

**Comment by indpurvesh** [comment]
I just changed the label `Pay at Pickup`
