### ISSUE TITLE
HTML code is displayed as plaintext at frontpage

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#288]
![htmldisplay](https://user-images.githubusercontent.com/1594411/49535910-995c2a00-f8c5-11e8-81c9-9b2e098afc1e.PNG)

![html2knipsel](https://user-images.githubusercontent.com/1594411/49535998-cd374f80-f8c5-11e8-9239-e90c1e2bd484.PNG)

**Comment by indpurvesh** [comment]
I think this bug is part of `SimpleMDE` Markdown editor change over from summernote. But it should be fixed in Dev. Need more testing though. I have change the dummy data so it should be fixed.

**Comment by ghermans** [comment]
Issue sill occurs in 2.9.8

**Comment by indpurvesh** [comment]
Do you want to try with a fresh installation? it did work for me in a fresh installation.

**Comment by ghermans** [comment]
hmm strange because i actually did 2 fresh installs before i reopened the issue

**Comment by indpurvesh** [comment]
I will dig bit more I know the bug has come because of now I am using markdowns editor and in past I was using summernote editor.
