### ISSUE TITLE
Saving Attributes with Empty Field

### ISSUE THREAD

**Issue by ludioao** [avored/laravel-ecommerce#289]
Hello, 

I've tried to save attribute with 3 filled fields and 1 without any information and got an error:

``SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'display_text' cannot be null (SQL: insert into `avored_attribute_dropdown_options` (`display_text`, `attribute_id`, `updated_at`, `created_at`) values (, 2, 2018-12-07 20:30:07, 2018-12-07 20:30:07))``

Solved when I modify AttributeController@saveDropdownOptions.
```
 private function saveDropdownOptions($attribute, $request)
    {
        if (null !== $request->get('dropdown_options')) {
            if (null != $attribute->attributeDropdownOptions()->get() &&
                $attribute->attributeDropdownOptions()->get()->count() >= 0
                ) {
                $attribute->attributeDropdownOptions()->delete();
            }

            foreach ($request->get('dropdown_options') as $key => $val) {
                if ($key == '__RANDOM_STRING__' || empty($val['display_text'])) {
                    continue;
                }
                $attribute->attributeDropdownOptions()->create($val);
            }
        }
    }
```

**Comment by indpurvesh** [comment]
Thanks @ludioao its really nice bug. I do really liking the bug that you are raising. thanks for that.

I am working on your Product Attribute Bug too. This one is simple fix with

    if (empty($val)) {
        continue;
    }

Plus I am thinking of adding Laravel Form Request check too.

**Comment by ludioao** [comment]
Can't solve with empty($val), 'cause $val is an array with a key 'display_text'. 

My code fix is above.
