### ISSUE TITLE
Form Helper

### ISSUE THREAD

**Issue by ludioao** [avored/laravel-ecommerce#290]
@indpurvesh We should use this package to generate Forms :)

Look there
https://github.com/netojose/laravel-bootstrap-4-forms

**Comment by indpurvesh** [comment]
When i stated it i did stated using something simple and the idea was to improve as it goes.

[https://github.com/avored/framework/tree/master/resources/views/forms](Form Field Template)

Then I did think of building my own Vue Form Component but now again I am thinking of removing vue completely and use the only jquery.

**Comment by ludioao** [comment]
Sure, but this package doesn't use any dependency like Laravel Collective or something. 

basically same as your idea, but a little better...

**Comment by indpurvesh** [comment]
I had quickly see that package as you have given me a link. Once I will fix some very important task (specially your attribute one) then I will think and work on making app/package more stable and use the best possible practice and I am working on PHPUnit test coverage improvements too.

**Comment by indpurvesh** [comment]
Sorry i am not implementing that helper in this package
