### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Jkmorais** [avored/laravel-ecommerce#293]
Can someone help me? I'm trying to install AvoRed, but I'm getting this error:

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)```

**To Reproduce**
1. Create a new project with `$ composer create-project --prefer-dist avored/laravel-ecommerce`
2. Setup environment (.env)
3. Execute the AvoRed install command `$ php artisan avored:install`

**Screenshots**
![Screenshot](https://i.imgur.com/FX515Tg.png)

**Desktop:**
 - Browser: Chrome
 - Version: 70.0.3538.110

Thank You!

**Comment by indpurvesh** [comment]
Are you using `mysql` or some other databases?

**Comment by Jkmorais** [comment]
Yes. I'm using MariaDB (Version 10.1.36-MariaDB) from Xampp

**Comment by indpurvesh** [comment]
i never try maria db in my local so i will try and let you know more details. After seeing the error i have a feeling that `maria db` wont support `json` as a datatype which cause the bug. If you change the json to text it might work in your case.

**Comment by return0ir** [comment]
In vendor\avored\framework\database\migrations\2017_03_29_000000_avored_framework_schema.php change this line:
$table->json('product_info')->nullable()->default(null);
to:
$table->text('product_info')->nullable()->default(null);
it might solve your problem!

**Comment by Jkmorais** [comment]
Thanks @return0ir. It Works!

**Comment by Jkmorais** [comment]
> In vendor\avored\framework\database\migrations\2017_03_29_000000_avored_framework_schema.php change this line:
> $table->json('product_info')->nullable()->default(null);
> to:
> $table->text('product_info')->nullable()->default(null);
> it might solve your problem!

Thanks @return0ir , It Works!
