### ISSUE TITLE
Avored API

### ISSUE THREAD

**Issue by Jkmorais** [avored/laravel-ecommerce#295]
Hello. Is there any way to implement a Rest API in AvoRed for product listing (with images) and categories?

**Comment by indpurvesh** [comment]
Yes there is checkout ‘vendor/avored/framework/src/Api’ folder.

You need to do auth via passport and once you get nearer token then you can do 

Https:// siteurl/api/product and etc 

Route file is located at ‘vendor/avored/framework/routes/api.php’

**Comment by Jkmorais** [comment]
You mean bearer token?

**Comment by indpurvesh** [comment]
yes. You can follow this docs for more information because i am using an laravel passport pacakge for api authentication

https://laravel.com/docs/5.7/passport

**Comment by Jkmorais** [comment]
Thanks. I'll try it

**Comment by indpurvesh** [comment]
Let me know if you had any trouble.

**Comment by Jkmorais** [comment]
Is there a way to config API clients from Avored dashboard ?

**Comment by indpurvesh** [comment]
sorry not at this stage but idea is that in my mind. Once some important task gets finished i will work on it to get the token via avored admin dashboard.

**Comment by ghermans** [comment]
I strongly suggest not to manage api clients from the dashboard, instead add a tab / nav item at the user profile page.

**Comment by indpurvesh** [comment]
Ideally `passport` support two type of client auth 
 - user based token (get token based on via password auth)
 - app based token  (get token via client_Id & client_secret)

**Comment by ghermans** [comment]
I know, but even then the dashboard should only display data related to sales/products/invoices etc. 
unless we add a option to customize the dashboard (enable/disable widgets)

**Comment by indpurvesh** [comment]
Ofcourse not from the dashboard.

I would assume dashboard as @Jkmorais means by the `Admin=>Configuration=>Developer`

**Comment by Jkmorais** [comment]
Exactly. It would be very efficient to grab the direct access token in the dash under `Admin => Configuration => Developer`

**Comment by Jkmorais** [comment]
Now, I'm in doubt, how to configure passport lib. I have already installed using `$ composer require laravel/passport` and `php artisan passport:install` Now I do not know how to proceed

**Comment by indpurvesh** [comment]
You dont have to install it have been part of `avored/framework` and passport:install is done via avored:install too

**Comment by indpurvesh** [comment]
Start reading from how to issue an access token

https://laravel.com/docs/5.7/passport#issuing-access-tokens

Where to find your client_id and client_secret

 Admin => Settings => Staff => click Show API

**Comment by Jkmorais** [comment]
Ok. I'll do it.

**Comment by Jkmorais** [comment]
One more thing, I took a look at the `Product::get()` method and saw that it only returns the product infos. How do I get product images?

**Comment by indpurvesh** [comment]
Checkout these file 

`vendor/avored/framework/src/Models/Database/Product.php`

    $product->images // product images
    $product->categories // product categories and etc

**Comment by Jkmorais** [comment]
Are the composer package up-to-date? Here the API route is `appdomain.tdl/api/v1/*`

**Comment by ghermans** [comment]
hmm strange the composer package is the same as the GitHub repository

**Comment by indpurvesh** [comment]
@ghermans yes you right.

@Jkmorais I think you understand it wrong I guess as soon as you do `composer create-project` or `composer install` it should install the required packages.

**Comment by Jkmorais** [comment]
Guys, I'm getting this error, when calling API: `Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by indpurvesh** [comment]
Ideally you should not have a different domain. I would suggest to use sub domain.

During deveopment time you can do this to fix the problem.

 open a file `bootstrap/app.php` and put the below code on top

    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: *');
    header('Access-Control-Allow-Headers: *');
