### ISSUE TITLE
Problems with creating user on Admin site.

### ISSUE THREAD

**Issue by mnce92** [avored/laravel-ecommerce#296]
**Describe the bug**
Cant add new user on admin site

**To Reproduce**
1. On admin site, go to 'Customers'
2. Click on 'Overview' and then "Create User"
3. Fill up all details and then click "Create User"
4. Nothing happen. No user created.

**Desktop (please complete the following information):**
 - Google Chrome
 - Version 70.0.3538.110 

**Additional context**

**Comment by indpurvesh** [comment]
@mnce92 thanks for raising the bug. It has been fixed and in `dev` branch. As soon as i will do next release it will get merge into master branch.
