### ISSUE TITLE
[product .order-status._fields] not found.

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#299]
**Describe the bug**
`
View [product .order-status._fields] not found. (View: /home/vagrant/avored/vendor/avored/framework/resources/views/product/order-status/create.blade.php)
`

**To Reproduce**
1. Go to **Orders**
2. Click on **Order-Status**
3. Click on **Create order status**

**Screenshots**
![error](https://user-images.githubusercontent.com/1594411/50341896-fc35fe00-0520-11e9-8926-fa080b6c8439.PNG)

**Comment by indpurvesh** [comment]
Fixed and move the controller and view files into Order folder instead of `Product`
