### ISSUE TITLE
Trying to get property 'menus' of non-object (View: C:\wamp64\www\laravel-ecommerce-master\themes\avored\default\views\home\index.blade.php)

### ISSUE THREAD

**Issue by humzazahid** [avored/laravel-ecommerce#303]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**
C:\wamp64\www\laravel-ecommerce-master\app\Http\ViewComposers\LayoutAppComposer.php
    ) {
        $this->menuGroupRepository = $menuGroupRepository;
        $this->siteCurrencyRepository = $currencyRepository;
    }
 
    /**
     * Bind data to the view.
     *
     * @param  View $view
     * @return void
     */
    public function compose(View $view)
    {
        $cart = (null === Session::get('cart')) ? 0 : count(Session::get('cart'));
        $menuGroup = $this->menuGroupRepository->query()->whereIsDefault(1)->first();
        $currencies = $this->siteCurrencyRepository->options();
        $metaTitle = Configuration::getConfiguration('general_site_title');
        $metaDescription = Configuration::getConfiguration('general_site_description');
 
        $view->withMenus($menuGroup->menus)
            ->withCart($cart)
            ->withCurrencies($currencies)
            ->withMetaTitle($metaTitle)
            ->withMetaDescription($metaDescription);
    }
}
 
Arguments
"Trying to get property 'menus' of non-object (View: C:\wamp64\www\laravel-ecommerce-master\themes\avored\default\views\home\index.blade.php)"

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by indpurvesh** [comment]
Have you changed anything on the backend? like trying to change the order of menu or anything?

**Comment by indpurvesh** [comment]
@humzazahid I have fixed it and commit on `dev` branch so when in next release it will come to master branch
