### ISSUE TITLE
Verify Your Email Address，Bug？

### ISSUE THREAD

**Issue by 635168775** [avored/laravel-ecommerce#306]
Swift_TransportException
Process could not be started

**Comment by indpurvesh** [comment]
Have you set up your mail setting properly? Follow this laravel docs for more information.

https://laravel.com/docs/5.7/mail

**Comment by 635168775** [comment]
Thanks

**Comment by ghermans** [comment]
Closing this issue since no new information has been provided.
Please reopen this issue with recent information if the problem still occurs.
