### ISSUE TITLE
Cant checkout items using "PlaceOrder"

### ISSUE THREAD

**Issue by mnce92** [avored/laravel-ecommerce#308]
**Describe the bug**
PlaceOrder at Check Out page isnt responding

**To Reproduce**
1. Add any items to cart
2. Go to cart and click checkout
3. fill in everything and click checkout
4. Nothing happen. 

**Desktop (please complete the following information):**
google Chrome (Version 71.0.3578.98)

**Comment by mnce92** [comment]
Addition: somehow it's working now, but the problem happen for around half an hour without any error

**Comment by indpurvesh** [comment]
Place Order button is disabled as default and once you select your shipping and payment option and etc then it gets enabled using JS.
