### ISSUE TITLE
Product properties relation

### ISSUE THREAD

**Issue by bonucci** [avored/laravel-ecommerce#309]
Hello, i notice in the product_property_varchar and other tables type i notice that there is in 2 columns that are "property_id" and "product_id", why  dont just create one column called "product_properties_id" that is the relation of the table "product_properties" ?

**Comment by indpurvesh** [comment]
Yes, we need both values. this way you can use the same properties to a different product as well.

**Comment by ghermans** [comment]
Closing this issue since the question has been answered by @indpurvesh, in case you believe your question isn't answered then reopen it and add more info.
