### ISSUE TITLE
GPDR compliance

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#312]
To comply with GPDR a default policy page should be added to the frontend page which contains the information that is stored by the system.
Also customers need to have a option in the account section to delete their profile.

#### CMS
- [ ] Create a default policy page that contains the information how long customer data is stored after removal + why the data is being used.

#### Customer portal
- [ ] Add a option to opt-out the customer from the store newsletter.
- [x] Add a button on the customer portal to remove the account.
- [x] If the customer clicks on the button display a model to confirm.

**Comment by indpurvesh** [comment]
On Privacy Page  we need to 
thanks, @ghermans for the knowledge.

all we need to do is write how long we keep the customer data (name, address etc) after he removes his account.

**Comment by indpurvesh** [comment]
BackEnd Menu has been added too with destroy permanently user record
