### ISSUE TITLE
checkbox is bug?

### ISSUE THREAD

**Issue by 635168775** [avored/laravel-ecommerce#313]
![image](https://user-images.githubusercontent.com/3425179/51096770-01255f00-17fa-11e9-972e-1330ae9b4c4a.png)

**Comment by indpurvesh** [comment]
@635168775 
What is your idea behind using checkbox with more option (Display Text)? As long as i remember i was using Display Text Option as a dropdown option list only. I never think of using it as checkbox option?

I would like to understand what is your idea behind using it? So i will think and then implement that feature too.

**Comment by 635168775** [comment]
Multiple selection
![image](https://user-images.githubusercontent.com/3425179/51176052-e97fd080-18f6-11e9-802f-ad98a56a1e96.png)

**Comment by 635168775** [comment]
Administrator system has bugs，Multiple selection is not supported.

**Comment by indpurvesh** [comment]
So you want an extra feature, for example, multiple selections? 

For example, you want the filter to work with `Red` and `Blue` both color product should display on category page?

**Comment by 635168775** [comment]
Yes,multiple selections,thanks.
![1](https://user-images.githubusercontent.com/3425179/51294599-9a4cb380-1a4e-11e9-89b5-1cebc27553f2.png)

**Comment by ghermans** [comment]
Keep in mind that we speak english, so providing us text in i guess Chinese? isn't always useful to explain something :)

**Comment by 635168775** [comment]
Sorry:)
