### ISSUE TITLE
Add the option to enable or disable sending invoices when order is created

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#316]
**Describe the solution you'd like**
The title should already explain it, there should be a option to generate and email the invoice directly when the order is created.

**Comment by indpurvesh** [comment]
Why do you think we need an option? isn't it should be an automatically send in all the case?

**Comment by ghermans** [comment]
Well i know stores who first send a order confirmation by email, when the order is shipped they send the invoice + tracking code.

Also at this moment you need to click on **Send invoice** from the backend, at least from my experience?

**Comment by indpurvesh** [comment]
Yes you right. Might add a Configuration Flag and then add this feature too.
