### ISSUE TITLE
Unable to run migration when using MariaDB

### ISSUE THREAD

**Issue by gmattworld** [avored/laravel-ecommerce#317]
After cloning the repository and setting up .env, I tried running
   
`php artisan avored:install -v`

**I got the following error: ** 
 Do you want to Install Dummy Data? (y/n) [yes]:
 > y

Application key set successfully.
Migration table created successfully.
Migrating: 2017_03_29_000000_avored_framework_schema

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1 (SQL: create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB)

  at C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php: 664
  660:         // If an exception occurs when attempting to run a query, we'll format the error
  661:         // message to include the bindings with SQL, which will make this exception a
  662:         // lot more helpful to the developer instead of just the database's errors.
  663:         catch (Exception $e) {
  664:             throw new QueryException(
  665:                 $query, $this->prepareBindings($bindings), $e
  666:             );
  667:         }
  668:
  669:         return $result;

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `created_at` timestamp null, `updated_at` timestamp null) default cha' at line 1")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 452

  2   PDO::prepare("create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 452

  3   Illuminate\Database\Connection::Illuminate\Database\{closure}("create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB", [])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 657

  4   Illuminate\Database\Connection::runQueryCallback("create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB", [], Object(Closure))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 624

  5   Illuminate\Database\Connection::run("create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB", [], Object(Closure))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 459

  6   Illuminate\Database\Connection::statement("create table `avored_order_product` (`id` int unsigned not null auto_increment primary key, `product_id` int unsigned not null, `order_id` int unsigned not null, `qty` int not null, `price` decimal(11, 6) not null, `tax_amount` decimal(11, 6) not null, `product_info` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci' engine = InnoDB")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php : 97

  7   Illuminate\Database\Schema\Blueprint::build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php : 264

  8   Illuminate\Database\Schema\Builder::build(Object(Illuminate\Database\Schema\Blueprint))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php : 165

  9   Illuminate\Database\Schema\Builder::create("order_product", Object(Closure))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php : 237

  10  Illuminate\Support\Facades\Facade::__callStatic("create")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\avored\framework\database\migrations\2017_03_29_000000_avored_framework_schema.php : 153

  11  AvoredFrameworkSchema::up()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php : 360

  12  Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php : 367

  13  Illuminate\Database\Migrations\Migrator::runMigration(Object(AvoredFrameworkSchema), "up")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php : 178

  14  Illuminate\Database\Migrations\Migrator::runUp("C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\avored\framework\src/../database/migrations/2017_03_29_000000_avored_framework_schema.php")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php : 147

  15  Illuminate\Database\Migrations\Migrator::runPending([])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php : 96

  16  Illuminate\Database\Migrations\Migrator::run([])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php : 71

  17  Illuminate\Database\Console\Migrations\MigrateCommand::handle()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  18  call_user_func_array([])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  19  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 87

  20  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 31

  21  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\Container.php : 572

  22  Illuminate\Container\Container::call()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Console\Command.php : 183

  23  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\symfony\console\Command\Command.php : 255

  24  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Console\Command.php : 170

  25  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Console\Command.php : 198

  26  Illuminate\Console\Command::call("migrate")
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\avored\framework\src\Support\Console\InstallCommand.php : 59

  27  AvoRed\Framework\Support\Console\InstallCommand::handle()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  28  call_user_func_array([])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  29  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 87

  30  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 31

  31  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Container\Container.php : 572

  32  Illuminate\Container\Container::call()
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Console\Command.php : 183

  33  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\symfony\console\Command\Command.php : 255

  34  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Console\Command.php : 170

  35  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\symfony\console\Application.php : 901

  36  Symfony\Component\Console\Application::doRunCommand(Object(AvoRed\Framework\Support\Console\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\symfony\console\Application.php : 262

  37  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\symfony\console\Application.php : 145

  38  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Console\Application.php : 89

  39  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php : 122

  40  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\xampp\htdocs\tecommerce\laravel-ecommerce\artisan : 35

**Comment by ghermans** [comment]
In vendor\avored\framework\database\migrations\2017_03_29_000000_avored_framework_schema.php

change this line:
```php
$table->json('product_info')->nullable()->default(null);
```
to:
```
$table->text('product_info')->nullable()->default(null);
```
