### ISSUE TITLE
Is there a pop-up box?

### ISSUE THREAD

**Issue by 635168775** [avored/laravel-ecommerce#319]
![image](https://user-images.githubusercontent.com/3425179/51363853-d6e2e280-1b14-11e9-9ff9-87051765e34b.png)

**Comment by 635168775** [comment]
How can we modify it?
![image](https://user-images.githubusercontent.com/3425179/51364002-67b9be00-1b15-11e9-9c0b-19151500ebc4.png)

**Comment by indpurvesh** [comment]
Try these

    var myEditor = new SimpleMDE({
      toolbar: [
          {
            name: "newImageIcon",
             action: customImageIconFunction,
            className: "fa fa-bold", // Look for a suitable icon
            title: "Custom Upload Image",
        }
    ]
    });

    function customImageIconFunction(editor) {

        var cm = editor.codemirror;
        var output = '';
        var selectedText = cm.getSelection();
        var text = selectedText || 'placeholder';

        output = '!!' + text + '!!';
       cm.replaceSelection(output);
    }

**Comment by ghermans** [comment]
Closing this issue as it should be resolved with the answer provided by @indpurves.    
If not please reopen it with more info.
