### ISSUE TITLE
Admin Template integration proper way

### ISSUE THREAD

**Issue by jariesdev** [avored/laravel-ecommerce#330]
Hi,

I would like to know what will the best way to change the entire admin GUI. Im planning to use admin template on this like SB Admin or the like. I assume that module create is not suitable and  create theme is for front end only.If so, how can I achieve this? thanks

**Comment by indpurvesh** [comment]
@jariesdev No, I am not looking to update or allow custom theme for the backend?

**Comment by jariesdev** [comment]
There is no way for not to update admin UI, is that right? how about removing existing routes?

**Comment by indpurvesh** [comment]
@jariesdevI think you miss understood a little bit. What  I am saying is: No at this stage there no idea to allow custom theme for admin.

In your copy, you can do whatever you like?

**Comment by jariesdev** [comment]
I'm just looking for a official way to do that. anyway, I need to dive deeper on your library to understand it more :) Thank you
