### ISSUE TITLE
admin menu  option not working

### ISSUE THREAD

**Issue by Jawwad-Parekh** [avored/laravel-ecommerce#332]
![image](https://user-images.githubusercontent.com/30830258/54979353-2c49ce80-4f60-11e9-9ed6-06d57dcc9917.png)
 i can't able drag and drop menu and also after submitted it giving error

**Comment by Mr3agle** [comment]
I got the same problem :c

**Comment by indpurvesh** [comment]
@Jawwad-Parekh, @Mr3agle  yes i just realize that i did a wrong commit and it part of release so soon new release is coming.


If you add an app.js in your layout file it will resolve the problem.

Open a file at: `vendor/avored/framework/resources/views/layouts/app.blade.php` at the bottom before closing body tag

    <script src="{{ url('vendor/avored-admin/js/vue.js') }}"></script>
    <script src="{{ url('vendor/avored-admin/js/app.js') }}"></script>

Hope this would fixed the problem.

**Comment by indpurvesh** [comment]
This bug would cause the problem during product create/edit screen too. because of missing javascript files.

**Comment by indpurvesh** [comment]
@Jawwad-Parekh Update on this issue:

Progress: 80% done
 
Just need more testing and few changes on backend side needed too because now I am using Vue-sortable component.
