### ISSUE TITLE
App Crash when creating submenu on admin panel, it cannot find the menu.menu-tree

### ISSUE THREAD

**Issue by Mr3agle** [avored/laravel-ecommerce#333]
When trying to drag the a category into the parent category on admin panel all the app crashes and cannot find the files that are in vendor/avored/.. and so on, after that, is not possible to access the front any more due to this exceptions.

**Comment by indpurvesh** [comment]
I just tried in my copy too. Yes, its a bug.

I think problems come when it tries to render the sub-nav for the navigation. @Mr3agle if you like to take this task and do a Pull Request you are welcome.

Otherwise, most likely I will fix it up in next release with #332
