### ISSUE TITLE
Declare Module Dependency

### ISSUE THREAD

**Issue by jariesdev** [avored/laravel-ecommerce#335]
I need to build a module which has a module dependency from other module. How can we archive this?

e.g. if we have base module for other module to rely on. after disabling it, other module should also disabled because it depends on the current base module.

Something like this:

```
identifier: avored-helloworld
name: Hello World
description: AvoRed Hello World Module
namespace: Avored\Helloworld\
status: Enabled
dependency: base-module
```

**Comment by indpurvesh** [comment]
Right now you can do it via composer but not via yaml file.

**Comment by jariesdev** [comment]
In case someone's looking for solution:

Usage, add this on your register.yml
`dependency: base-module`

register.yml (add dependency -- can be separated by comma  for multiple dependencies)
`identifier: avored-helloworld
name: Hello World
description: AvoRed Hello World Module
namespace: Avored\Helloworld\
status: Enabled
dependency: base-module
`
AvoRed\Framework\Modules (add)
`
protected $dependencies = [];

public function dependencies($dependencies = [])
    {
        if (count($dependencies) <= 0) {
            return $this->dependencies;
        }

        $this->dependencies = $dependencies;
        return $this;
    }
`

AvoRed\Framework\Modules\Manager
`
// remove this codes after $module->publishedTags($data['published_tags'] ?? []);
$composerLoader = require base_path('vendor/autoload.php');
if (strtolower($module->status()) == 'enabled') {
	$path = $iterator->getPath() . DIRECTORY_SEPARATOR . 'src';
	$composerLoader->addPsr4($module->namespace(), $path);
	$moduleProvider = $module->namespace() . 'Module';
	App::register($moduleProvider);
}

//replace above with this
$dependencies = empty($data['dependencies'])
    ? [] : explode(',', str_replace(' ', '', $data['dependencies']));
    $module->dependencies($dependencies);

// add this just after while loop
$this->moduleList = $this->sortByDependency($this->moduleList);
$this->moduleList->each(function ($module) {
$composerLoader = require base_path('vendor/autoload.php');
if (strtolower($module->status()) == 'enabled') {
    $path = $module->basePath() . DIRECTORY_SEPARATOR . 'src';
    $composerLoader->addPsr4($module->namespace(), $path);
    $moduleProvider = $module->namespace() . 'Module';
    App::register($moduleProvider);
}
});

// and lastly, add this function
public function sortByDependency(Collection $moduleList)
    {
        $modules = $moduleList->sort(function ($moduleA, $moduleB) {
            if (count($moduleA->dependencies()) === 0 && count($moduleA->dependencies()) === 0) {
                return 0;
            }

            if (in_array($moduleA->identifier(), $moduleB->dependencies())) {
                return -1;
            } else {
                return 1;
            }

        });
        return $modules;
    }
`

**Comment by indpurvesh** [comment]
@jariesdev i can see what you have done it. 

Why not you do a PR on the framework dev branch.

**Comment by jariesdev** [comment]
Sure my pleasure. I assume thats gonna be on the core framework right?

**Comment by indpurvesh** [comment]
Yes it’s the core framework.
