### ISSUE TITLE
Security issue Customer Address

### ISSUE THREAD

**Issue by bonucci** [avored/laravel-ecommerce#336]
It should have a Gate or a Policy in crud actions with the customer account.
I can update the address of other customer by changing the id from the edit address form.

Route example:
` http://localhost:8888/my-account/address/4`

AddressController:
```
 public function update(AddressRequest $request, Address $address)
    {
        $address->update($request->all());
        return redirect()->route('my-account.address.index');
    }
```

Solution:
AddressPolicy
Link help:https://laravel.com/docs/5.7/authorization#creating-policies

**Comment by indpurvesh** [comment]
Thanks @bonucci its fixed in dev branch.
