### ISSUE TITLE
Add to cart with 0 Quantity.

### ISSUE THREAD

**Issue by mkraha** [avored/laravel-ecommerce#337]
I found an issue on add to cart when I use 0 quantity. It should not add to cart and throw an error message if the quantity is 0 and not to show in cart.
![image](https://user-images.githubusercontent.com/6831562/55944195-5ed61580-5c48-11e9-950d-8d799120d8fc.png)

Cart with 0 quatity item:
![image](https://user-images.githubusercontent.com/6831562/55944256-85944c00-5c48-11e9-8ca5-12b338e52220.png)

**Comment by indpurvesh** [comment]
@mkrahamath Fixed in dev branch

**Comment by mkrahamath** [comment]
Thanks
