### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by hamzaelhoub** [avored/laravel-ecommerce#338]
![la](https://user-images.githubusercontent.com/12114256/55947186-e9694580-5c45-11e9-94b3-17b0004ae344.png)

**Comment by indpurvesh** [comment]
Problem is you are using mariaDB as a database and mariaDB don't support json fields.

If you are doing an development only then i would suggest you can go to this file..

`vendor/avored/framework/database/migrations/2017_03_29_000000_avored_framework_schema.php` 

around line no: 156

replace this line 

     $table->text('product_info')->nullable()->default(null);
