### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by dmgiri** [avored/laravel-ecommerce#342]
**Describe the bug**
Unable to register a user.

**To Reproduce**
1. Go to 'http://127.0.0.1:8000/register'
2. Click on 'Register'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/25407117/56462247-aba2b480-63dd-11e9-9b3d-55b509c211d5.png)

```
        if ($err = stream_get_contents($pipes[2])) {
            throw new Swift_TransportException(
                'Process could not be started ['.$err.']'
                );
        }
```
**Desktop (please complete the following information):**
 - Firefox [e.g. chrome, safari]
 - 66.0.3 [e.g. 22]

**Comment by indpurvesh** [comment]
Its not a bug. you need to do your mail setup. 

In dev if you don't want to send an email then open your `.env` file 

    MAIL_DRIVER=mail // change this line
    MAIL_HOST=smtp.mailtrap.io

**Comment by dmgiri** [comment]
How to test without mail server?

**Comment by indpurvesh** [comment]
open your env file and replace the code like below

    MAIL_DRIVER=mail // change this line
