### ISSUE TITLE
error in create page http://localhost:8000/admin/page/create

### ISSUE THREAD

**Issue by aryby** [avored/laravel-ecommerce#343]
in admin panel when i wanna create a new page (or edit a page existe like home page )
error like 
![page](https://user-images.githubusercontent.com/37639238/57261643-33342880-7058-11e9-9218-8e5082560230.PNG)

nb: 
button destroy (delete product or delete page not work  )
destroy in (exemple  http://localhost:8000/admin/product/14 and http://localhost:8000/admin/page/1)

**Comment by indpurvesh** [comment]
@aryby will fix soon.

**Comment by indpurvesh** [comment]
I have fixed it in dev branch. during next release it will be available.
