### ISSUE TITLE
Undefined variable: page

### ISSUE THREAD

**Issue by Resin01** [avored/laravel-ecommerce#344]
Just installed avored but I cannot seem to create new pages.

1. Go to '/admin/page/create
2. See error

I get the following error.
Undefined variable: page (View: /var/www/avored/vendor/avored/framework/resources/views/cms/page/_fields.blade.php) (View: /var/www/avored/vendor/avored/framework/resources/views/cms/page/_fields.blade.php)

**Comment by indpurvesh** [comment]
@Resin01 

I think that bug was fixed in the dev branch. it has not been released yet.

If you want to do a dirty fix in the mean time we release the next version you can take these file
https://github.com/avored/framework/blob/dev/resources/views/cms/page/_fields.blade.php
