### ISSUE TITLE
cant edit or add a product, save button is disabled

### ISSUE THREAD

**Issue by adrilevendi** [avored/laravel-ecommerce#356]
Whenever I want to add or edit a product the save button at the end is disabled. I tried filling all the fields but didn't work.

**Comment by indpurvesh** [comment]
Can you please provide some more information.

Which version of avored are you using?

Can you share a screenshot of your console log? 
I have a feeling that you have some JS console error which causes this bug to raised.

**Comment by adrilevendi** [comment]
Console screenshots below. I dont know where to look for the version, but I have 2 weeks since I downloaded it . I also got another copy today and it was the same.
XAMPP 3.2.4 PHP 7.2.19 Win10x64, MySQL 10.3.16-MariaDB

![5](https://user-images.githubusercontent.com/50158348/61190199-e3499180-a698-11e9-937a-a04ad1e4517a.png)
![6](https://user-images.githubusercontent.com/50158348/61190200-e3e22800-a698-11e9-8c2e-b71e45a6a414.png)

**Comment by indpurvesh** [comment]
You have been using an older version.

Can you please open this file `vendor/avored/framework/resources/views/layouts/app.blade.php`

 and put the below code just before body tag then it should work.

`<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>`

**Comment by adrilevendi** [comment]
Added the script at vendor\avored\framework\resources\views\layouts\app.blade.php ,
but thw same thing happens again ."jQuery is not defined".

![image](https://user-images.githubusercontent.com/50158348/61232391-7c76b780-a72e-11e9-89a5-ec263ceacc57.png)
![image](https://user-images.githubusercontent.com/50158348/61232584-f60ea580-a72e-11e9-9004-74d2e81675fa.png)

I don't know why but the line 865 that console is referencing leads to the login html
![image](https://user-images.githubusercontent.com/50158348/61232705-3cfc9b00-a72f-11e9-80af-63a7322ab133.png)

**Comment by indpurvesh** [comment]
@adrilevendi i would suggest better to use the latest alpha5 version instead of that one.
