### ISSUE TITLE
Create page and edit page throws error

### ISSUE THREAD

**Issue by adrilevendi** [avored/laravel-ecommerce#357]
Throws this error whenever I click create or edit page.

The below is from edit, but they're pretty much the same 
http://localhost:8000/admin/page/1/edit

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Call to undefined method AvoRed\Framework\Models\Database\AdminUser::isInWishlist() (View: C:\xampp\htdocs\avored\themes\avored\default\views\product\view\product-card.blade.php) (View: C:\xampp\htdocs\avored\themes\avored\default\views\product\view\product-card.blade.php)

 GET Data empty
POST Data empty 
DOCUMENT_ROOT | "C:\xampp\htdocs\avored\public"
-- | --
REMOTE_ADDR | "127.0.0.1"
REMOTE_PORT | "59284"
SERVER_SOFTWARE | "PHP 7.2.19 Development Server"
SERVER_PROTOCOL | "HTTP/1.1"
SERVER_NAME | "127.0.0.1"
SERVER_PORT | "8000"
REQUEST_URI | "/admin/page/1/edit"
REQUEST_METHOD | "GET"
SCRIPT_NAME | "/index.php"
SCRIPT_FILENAME | "C:\xampp\htdocs\avored\public\index.php"
PATH_INFO | "/admin/page/1/edit"
PHP_SELF | "/index.php/admin/page/1/edit"
HTTP_HOST | "localhost:8000"
HTTP_USER_AGENT | "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
HTTP_ACCEPT | "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_LANGUAGE | "en-US,en;q=0.5"
HTTP_ACCEPT_ENCODING | "gzip, deflate"
HTTP_REFERER | "http://localhost:8000/admin/page"
HTTP_CONNECTION | "keep-alive"
HTTP_COOKIE | "remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkxFS1lidFFmVGtYcllhQkRZejBsRFE9PSIsInZhbHVlIjoiUGp0WURsdGt1eGNqTlJLYVpTU1hEU0NGU1QzVzV5dzRqaTVCSD "
HTTP_UPGRADE_INSECURE_REQUESTS | "1"
REQUEST_TIME_FLOAT | 1563090736.8511
REQUEST_TIME | 1563090736

**Comment by indpurvesh** [comment]
`C:\xampp\htdocs\avored\themes\avored\default\views\product\view\product-card.blade.php` these are view path for the frontend theme.

I am not sure how come you have a frontend theme inside a backend path. I am not sure what is happening there.

**Comment by adrilevendi** [comment]
Yes. I know it makes no sense. I think its trying to call the IsInWishList() fn for the user wihich is Admin but
the AdminUser class doesn't have a wishlist. Even then it has a totally different path, I don't know how could it happen. I haven't modified any file from the views.

**Comment by indpurvesh** [comment]
@adrilevendi 
I would rather suggest better use of the latest version. I know because of the wrong `webpack.mix.js` set up that particular version has so many bugs.

**Comment by kamellochile** [comment]
hello all! I had installed the latest version and throws the same error. Can somebody tell me if in the last version was fixed?

**Comment by indpurvesh** [comment]
@kamellochile yes it has been fixed in the new version. I haven't done a proper release yet just done an alpha5 version yet.

**Comment by danielgara** [comment]
@indpurvesh Can you explain me how to download the new version? I have followed the steps in avored website.
However this command "composer create-project --prefer-dist avored/laravel-ecommerce" always downloads the laravel-ecommerce 2.9.9 which is not compatible with avored framework 3.* and I always get the problems described by the other people in this thread.

Thanks!!

**Comment by indpurvesh** [comment]
@danielgara try this way:

`composer create-project --prefer-dist avored/laravel-ecommerce=3.0.0-beta-3`

**Comment by indpurvesh** [comment]
your admin login screen should look something like below.

<img width="1283" alt="Screen Shot 2019-08-18 at 1 39 21 PM" src="https://user-images.githubusercontent.com/4218702/63219048-a738ad80-c1bd-11e9-875c-1ec43203184b.png">

**Comment by indpurvesh** [comment]
These both should be fixed in the latest version
