### ISSUE TITLE
Undefined method on homepage

### ISSUE THREAD

**Issue by ghermans** [avored/laravel-ecommerce#359]
**Describe the bug**

"Call to undefined method AvoRed\Framework\Database\Repository\ProductRepository::getAllWithoutVaiation()"

**To Reproduce**
1. Setup a fresh install **git clone https://github.com/avored/laravel-ecommerce**
2. run **php artisan avored:install**
3. Visit the homepage and see the error

**Comment by indpurvesh** [comment]
@ghermans do you want to try `composer update` that method does exist on latest [framework](https://www.github.com/avored/framework)

**Comment by indpurvesh** [comment]
@ghermans this bug should be fixed with new beta release
