### ISSUE TITLE
Cannot be added to cart

### ISSUE THREAD

**Issue by caromatias** [avored/laravel-ecommerce#360]
**Describe the bug**

Too few arguments to function AvoRed\Framework\Cart\Manager::createCartProductFromSlug(), 1 passed

**To Reproduce**

The method to add to cart expects a collection attributes, the error is in **vendor/avored/framework/src/Cart/Manager.php on line 101 and exactly 2 expected**

I'm using the alpha5

**Comment by indpurvesh** [comment]
@caromatias I have fixed that bug in my development branch already so in next release it should be fixed.

**Comment by indpurvesh** [comment]
@caromatias this bug should be fixed with new beta release
