### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by projct1** [avored/laravel-ecommerce#368]
Hello)

When will laravel 6.0 support be implemented?

**Comment by ghermans** [comment]
Strange questions since hat version isn't even released yet.
https://laravel-news.com/is-laravel-6-0-out-yet

**Comment by indpurvesh** [comment]
@ghermans i agree.
Plus @projct1 if you simply use the package with laravel 6.0 version i don't think it would break anything. As i have read the docs doesn't feel like there are any breaking changes.  Still waiting for an official release then work on the upgrade.

**Comment by projct1** [comment]
Ok, thanks)

**Comment by indpurvesh** [comment]
update on this issue.

I am using laravel 6 in `dev` branch. all seems working fine and unit test running fine too. just need to do some more testing and make sure all is working.
