### ISSUE TITLE
I cannot upload an image or save a product 

### ISSUE THREAD

**Issue by mikeyapina** [avored/laravel-ecommerce#369]
product.php is giving an error when i open the code begins around line 133 = the red error says - language features not compatible.

I am using PhP 7.2 - also what is significant is I cannot do the following:

1. when i pick an image to upload nothing happens other than teh item name is put into box but no image is presented or anything just name

2. the Save Product is gray so i can't pick it even though i have made other changes on teh product page

========== comnde in file with error marler ====
    public function saveProductImages(array $data):self
    {
        if (isset($data['image']) && count($data['image']) > 0) {
            $exitingIds = $this->images()->get()->pluck('id')->toArray();
            foreach ($data['image'] as $key => $data) {
                if (is_int($key)) {
                    if (($findKey = array_search($key, $exitingIds)) !== false) {
                        $productImage = ProductImage::findorfail($key);
                        $productImage->update($data);
                        unset($exitingIds[$findKey]);
                    }
                    continue;
                }
                ProductImage::create($data + ['product_id' => $this->id]);
            }
            if (count($exitingIds) > 0) {
                ProductImage::destroy($exitingIds);
            }
        }
        return $this;
    }

**Comment by indpurvesh** [comment]
I have feeling that you are using one of the buggy version. If you have just started development then i would suggest rather use this one . `https://github.com/avored/laravel-ecommerce/releases/tag/3.0.0-beta-3`.

you can simply use this command:
    composer create-project avored/laravel-ecommerce:3.0.0-beta-3

**Comment by indpurvesh** [comment]
If you like to make existing project work. Try adding jquery on your layouts/app.blade.php file. 

You will find a file in `vendor/avored/framework/resources/views/layouts/app.blade.php`

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

**Comment by mikeyapina** [comment]
Thanks your fresh install gave me this error at the end ..


> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()  
                                                                   

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by indpurvesh** [comment]
I have fixed that error in dev branch so in next release it won't be there.

But still, that error won't have any issue on application.

**Comment by mikeyapina** [comment]
ok for env i see new paramaters - how do i use them i am using aws uswest

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

**Comment by mikeyapina** [comment]
now i am getting this 

ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo chown -R www-data:www-data laravel-ecommerce
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo php artisan avored:install

                                                            
  There are no commands defined in the "avored" namespace.

**Comment by mikeyapina** [comment]
Now I am getting this...

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()

**Comment by indpurvesh** [comment]
Just run `composer update` command it should fixed `Menu::type` bug
