### ISSUE TITLE
issue <-- sudo php artisan avored:install

### ISSUE THREAD

**Issue by mikeyapina** [avored/laravel-ecommerce#370]
issue gave me this error .. I noticed in teh DB it had no tables when i started .. so this error is weird

---------

ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo php artisan avored:install
Migration table created successfully.
Migrating: 2017_03_29_000000_avored_framework_schema
Migrated:  2017_03_29_000000_avored_framework_schema (13.97 seconds)

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'inventory.users' doesn't exist (SQL: alter table `users` add `user_group_id` bigint unsigned null)

  at /var/www/html/store/laravel-ecommerce/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'inventory.users' doesn't exist")
      /var/www/html/store/laravel-ecommerce/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /var/www/html/store/laravel-ecommerce/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  Please use the argument -v to see more details.

**Comment by indpurvesh** [comment]
@mikeyapina

try running in these order

    php artisan migrate:fresh
    php artisan avored:install

**Comment by mikeyapina** [comment]
sadly just more issues ... sadly. After I ran that without erros adn added a admin account I tried to go to the /admin and this is the error

ErrorException (E_WARNING)
Illegal offset type in isset or empty

http://store.regenics.com/admin

a tad frustrating but appreciate your guidance.

**Comment by indpurvesh** [comment]
@mikeyapina 

honestly, I never had any of these error in past. 

I am not sure what these error is but my best `guess` i would say that `config/auth` it not merging properly which is very weired. It should happen in  `AvoRedProvider` file.

have you run `composer update` command?

**Comment by mikeyapina** [comment]
i understand .. i can only describe what is happening here i just ran it all again. One error prior siad i had to generster a key so i did that as another step.

But when i go to the url http://store.regenics.com/ same error


ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ php artisan key:generate
Application key set successfully.
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo run composer update
sudo: run: command not found
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: avored/framework
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ php artisan migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.14 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.14 seconds)
Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated:  2016_06_01_000001_create_oauth_auth_codes_table (0.19 seconds)
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated:  2016_06_01_000002_create_oauth_access_tokens_table (0.25 seconds)
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table (0.25 seconds)
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated:  2016_06_01_000004_create_oauth_clients_table (0.14 seconds)
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table (0.14 seconds)
Migrating: 2017_03_29_000000_avored_framework_schema
Migrated:  2017_03_29_000000_avored_framework_schema (14.17 seconds)
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ php artisan avored:install
Nothing to migrate.
AvoRed Install Successfully!

**Comment by mikeyapina** [comment]
so as a practice i went thru every step again .. the only error i get is the error we talked about at the beginning that you said not to worry about. But still the same issue happens again so i repeated everything with the same result.

ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo rm -R laravel-ecommerce
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo  composer create-project avored/laravel-ecommerce:3.0.0-beta-3
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing avored/laravel-ecommerce (3.0.0-beta-3)
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing avored/laravel-ecommerce (3.0.0-beta-3): Loading from cache
Created project in /var/www/html/store/laravel-ecommerce
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 107 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing symfony/yaml (v4.3.1): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Loading from cache
  - Installing vlucas/phpdotenv (v3.4.0): Loading from cache
  - Installing symfony/css-selector (v4.3.1): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/var-dumper (v4.3.1): Loading from cache
  - Installing symfony/routing (v4.3.1): Loading from cache
  - Installing symfony/process (v4.3.1): Loading from cache
  - Installing symfony/polyfill-php73 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.11.0): Loading from cache
  - Installing symfony/mime (v4.3.1): Loading from cache
  - Installing symfony/http-foundation (v4.3.1): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.1): Loading from cache
  - Installing symfony/event-dispatcher (v4.3.1): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.3.1): Loading from cache
  - Installing symfony/http-kernel (v4.3.1): Loading from cache
  - Installing symfony/finder (v4.3.1): Loading from cache
  - Installing symfony/service-contracts (v1.1.2): Loading from cache
  - Installing symfony/console (v4.3.1): Loading from cache
  - Installing symfony/polyfill-iconv (v1.11.0): Loading from cache
  - Installing doctrine/lexer (1.0.2): Loading from cache
  - Installing egulias/email-validator (2.1.8): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.1): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing ramsey/uuid (3.8.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing opis/closure (3.3.0): Loading from cache
  - Installing symfony/translation-contracts (v1.1.2): Loading from cache
  - Installing symfony/translation (v4.3.1): Loading from cache
  - Installing nesbot/carbon (2.19.2): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing league/flysystem (1.0.53): Loading from cache
  - Installing erusev/parsedown (1.7.3): Loading from cache
  - Installing dragonmantank/cron-expression (v2.3.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing laravel/framework (v5.8.24): Loading from cache
  - Installing avored/framework (dev-dev e6e7424): Loading from cache
  - Installing fideloper/proxy (4.1.0): Loading from cache
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing nikic/php-parser (v4.2.2): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.9.9): Loading from cache
  - Installing laravel/tinker (v1.0.8): Loading from cache
  - Installing sabberworm/php-css-parser (8.1.0): Loading from cache
  - Installing phenx/php-svg-lib (v0.3.2): Loading from cache
  - Installing phenx/php-font-lib (0.5.1): Loading from cache
  - Installing dompdf/dompdf (v0.8.3): Loading from cache
  - Installing barryvdh/laravel-dompdf (v0.8.4): Loading from cache
  - Installing beyondcode/laravel-dump-server (1.2.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Installing zendframework/zend-diactoros (2.1.2): Loading from cache
  - Installing symfony/psr-http-message-bridge (v1.2.0): Loading from cache
  - Installing phpseclib/phpseclib (2.0.18): Loading from cache
  - Installing league/event (2.2.0): Loading from cache
  - Installing lcobucci/jwt (3.3.1): Loading from cache
  - Installing defuse/php-encryption (v2.2.1): Loading from cache
  - Installing league/oauth2-server (7.4.0): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing firebase/php-jwt (v5.0.0): Loading from cache
  - Installing laravel/passport (v7.3.0): Loading from cache
  - Installing filp/whoops (2.3.1): Loading from cache
  - Installing nunomaduro/collision (v3.0.1): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (2.0.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (4.2.2): Loading from cache
  - Installing sebastian/diff (3.0.2): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpunit/php-timer (2.1.2): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
  - Installing theseer/tokenizer (1.1.3): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.0.1): Loading from cache
  - Installing phpunit/php-code-coverage (6.1.4): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.1): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing phpspec/prophecy (1.8.1): Loading from cache
  - Installing phar-io/version (2.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.9.1): Loading from cache
  - Installing phpunit/phpunit (7.5.13): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing orchestra/testbench-core (v3.8.5): Loading from cache
  - Installing mockery/mockery (1.2.2): Loading from cache
  - Installing orchestra/testbench (v3.8.3): Loading from cache
  - Installing webonyx/graphql-php (v0.13.5): Loading from cache
  - Installing rebing/graphql-laravel (v1.23.0): Loading from cache
  - Installing stripe/stripe-php (v6.38.0): Loading from cache
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/lock
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
symfony/translation suggests installing symfony/config
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (^3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (^2.6).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
laravel/framework suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (^1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (^4.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (^1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (^3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (^4.2).)
laravel/framework suggests installing wildbit/swiftmailer-postmark (Required to use Postmark mail driver (^3.0).)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
dompdf/dompdf suggests installing ext-gmagick (Improves image processing performance)
dompdf/dompdf suggests installing ext-imagick (Improves image processing performance)
symfony/psr-http-message-bridge suggests installing nyholm/psr7 (For a super lightweight PSR-7/17 implementation)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.6.0)
phpunit/phpunit suggests installing ext-soap (*)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
orchestra/testbench-core suggests installing orchestra/testbench-browser-kit (Allow to use legacy Laravel BrowserKit for testing (^3.8).)
orchestra/testbench-core suggests installing orchestra/testbench-dusk (Allow to use Laravel Dusk for testing (^3.8).)
webonyx/graphql-php suggests installing react/promise (To leverage async resolving on React PHP platform)
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()  
                                                                   

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo vi laravel-ecommerce/.env 
ubuntu@ip-172-31-1-145:/var/www/html/store$ php artisan migrate:fresh

   UnexpectedValueException  : The stream or file "/var/www/html/store/storage/logs/laravel-2019-08-30.log" could not be opened: failed to open stream: Permission denied

  at /var/www/html/store/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
    103|             }
    104|             restore_error_handler();
    105|             if (!is_resource($this->stream)) {
    106|                 $this->stream = null;
  > 107|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened: '.$this->errorMessage, $this->url));
    108|             }
    109|         }
    110| 
    111|         if ($this->useLocking) {

  Exception trace:

  1   Monolog\Handler\StreamHandler::write()
      /var/www/html/store/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php:119

  2   Monolog\Handler\RotatingFileHandler::write()
      /var/www/html/store/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:39

  Please use the argument -v to see more details.
ubuntu@ip-172-31-1-145:/var/www/html/store$ cd la*
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ php artisan migrate:fresh

In StreamHandler.php line 107:
                                                                                                                                                                
  The stream or file "/var/www/html/store/laravel-ecommerce/storage/logs/laravel-2019-08-30.log" could not be opened: failed to open stream: Permission denied  
                                                                                                                                                                

ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo php artisan migrate:fresh

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()  
                                                                   

ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ cd ..
ubuntu@ip-172-31-1-145:/var/www/html/store$     sudo chown -R www-data:www-data /laravel-ecommerc
chown: cannot access '/laravel-ecommerc': No such file or directory
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo chown -R www-data:www-data /laravel-ecommerce
chown: cannot access '/laravel-ecommerce': No such file or directory
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo chown -R www-data:www-data laravel-ecommerce
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo chmod o+w storage 
ubuntu@ip-172-31-1-145:/var/www/html/store$ sudo chmod -R 770 laravel-ecommerce
ubuntu@ip-172-31-1-145:/var/www/html/store$ cd  lar*
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo php artisan migrate:fresh

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()  
                                                                   

ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$   sudo usermod -a -G www-data ubuntu
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo php artisan migrate:fresh

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()  
                                                                   

ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo chgrp -R www-data storage bootstrap/cache
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo chmod -R ug+rwx storage bootstrap/cache
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo php artisan migrate:fresh

In AppServiceProvider.php line 33:
                                                                   
  Call to undefined method AvoRed\Framework\Menu\MenuItem::type()  
                                                                   

ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ composer update 
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 46 updates, 10 removals
  - Removing webonyx/graphql-php (v0.13.5)
  - Removing stripe/stripe-php (v6.38.0)
  - Removing sabberworm/php-css-parser (8.1.0)
  - Removing rebing/graphql-laravel (v1.23.0)
  - Removing phenx/php-svg-lib (v0.3.2)
  - Removing phenx/php-font-lib (0.5.1)
  - Removing orchestra/testbench-core (v3.8.5)
  - Removing orchestra/testbench (v3.8.3)
  - Removing dompdf/dompdf (v0.8.3)
  - Removing barryvdh/laravel-dompdf (v0.8.4)
  - Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
Loading from cache
  - Updating vlucas/phpdotenv (v3.4.0 => v3.5.0): Loading from cache
  - Updating symfony/css-selector (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/polyfill-php72 (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/var-dumper (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/routing (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/process (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/polyfill-php73 (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.11.0 => v1.12.0): Loading from cache
  - Updating symfony/mime (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/http-foundation (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/event-dispatcher-contracts (v1.1.1 => v1.1.5): Loading from cache
  - Updating symfony/event-dispatcher (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/debug (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/http-kernel (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/finder (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/service-contracts (v1.1.2 => v1.1.6): Loading from cache
  - Updating symfony/console (v4.3.1 => v4.3.4): Loading from cache
  - Updating symfony/polyfill-iconv (v1.11.0 => v1.12.0): Loading from cache
  - Updating doctrine/lexer (1.0.2 => 1.1.0): Loading from cache
  - Updating egulias/email-validator (2.1.8 => 2.1.11): Loading from cache
  - Updating opis/closure (3.3.0 => 3.3.1): Loading from cache
  - Updating symfony/translation-contracts (v1.1.2 => v1.1.6): Loading from cache
  - Updating symfony/translation (v4.3.1 => v4.3.4): Loading from cache
  - Updating nesbot/carbon (2.19.2 => 2.23.1): Loading from cache
  - Updating league/flysystem (1.0.53 => 1.0.55): Loading from cache
  - Updating laravel/framework (v5.8.24 => v5.8.34): Loading from cache
  - Updating zendframework/zend-diactoros (2.1.2 => 2.1.3): Loading from cache
  - Updating phpseclib/phpseclib (2.0.18 => 2.0.21): Loading from cache
  - Updating ralouphie/getallheaders (2.0.5 => 3.0.3): Loading from cache
  - Updating guzzlehttp/psr7 (1.5.2 => 1.6.1): Loading from cache
  - Updating laravel/passport (v7.3.0 => v7.4.0): Loading from cache
  - Updating symfony/yaml (v4.3.1 => v4.3.4): Loading from cache
  - Updating avored/framework (dev-dev e6e7424 => 3.0.4.1): Loading from cache
  - Updating fideloper/proxy (4.1.0 => 4.2.0): Loading from cache
  - Updating nikic/php-parser (v4.2.2 => v4.2.3): Loading from cache
  - Updating laravel/tinker (v1.0.8 => v1.0.10): Loading from cache
  - Updating beyondcode/laravel-dump-server (1.2.2 => 1.3.0): Loading from cache
  - Updating filp/whoops (2.3.1 => 2.5.0): Loading from cache
  - Updating mockery/mockery (1.2.2 => 1.2.3): Loading from cache
  - Updating sebastian/exporter (3.1.0 => 3.1.1): Loading from cache
  - Updating phpunit/php-token-stream (3.0.1 => 3.1.0): Loading from cache
  - Updating webmozart/assert (1.4.0 => 1.5.0): Loading from cache
  - Updating myclabs/deep-copy (1.9.1 => 1.9.3): Loading from cache
  - Updating phpunit/phpunit (7.5.13 => 7.5.15): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: avored/framework
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ sudo php artisan migrate:fresh
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.15 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.15 seconds)
Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated:  2016_06_01_000001_create_oauth_auth_codes_table (0.19 seconds)
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated:  2016_06_01_000002_create_oauth_access_tokens_table (0.25 seconds)
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table (0.26 seconds)
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated:  2016_06_01_000004_create_oauth_clients_table (0.14 seconds)
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table (0.14 seconds)
Migrating: 2017_03_29_000000_avored_framework_schema
Migrated:  2017_03_29_000000_avored_framework_schema (13.96 seconds)
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$ php artisan avored:install 
Nothing to migrate.
AvoRed Install Successfully!
ubuntu@ip-172-31-1-145:/var/www/html/store/laravel-ecommerce$

**Comment by indpurvesh** [comment]
I know why frontend error is happening because you have no products available. In my local I always install demo data so I never have that bug. I will fix that bug. 

But I am not sure why your `admin auth` `Illegal Offset type` error is coming up?

**Comment by indpurvesh** [comment]
Run this command to fixed the issue.

    php artisan avored:admin:make
