### ISSUE TITLE
Can't edit product

### ISSUE THREAD

**Issue by jamipietila** [avored/laravel-ecommerce#381]
I just installed Avored first time. For some reason, I cant add information to new product. The Save Product -button is disabled.

I added jquery to app.php layout as recommended in one bug report, and I'm not seeing "jquery missing" -error anymore, but the problem might be vue-related?

Any ideas what to try next?

**Comment by jamipietila** [comment]
Also some language strings seems to be missing:

![Screenshot 2019-09-15 at 12 47 07](https://user-images.githubusercontent.com/16705804/64919727-038bee80-d7b7-11e9-9600-8fe42aca7ff9.png)

**Comment by indpurvesh** [comment]
Yes, you are using one of my buggy version release (where i messed up webpack.mix.js). 

I would simply suggest please use the latest version should fix the problem.

    composer create-project avored/laravel-ecommerce:3.0.0

I would suggest better use the latest version.

As long as I remember that particular version was missing jquery so if you manually add CDN/jquery then I think all should work fine.

**Comment by jamipietila** [comment]
Ah, ok. Looks like I have php 7.1, what might explain that I don't have latest version. I will try that one out. Thanks!

**Comment by indpurvesh** [comment]
Let me know if you have any issue.

**Comment by jamipietila** [comment]
Hi!

Finally I had time to test the 3.0.0 version. Any ideas why I can't add product to shopping cart. I get error "Declaration of AvoRed\Framework\Cart\CartProduct::attributes($attributes = NULL) must be compatible with AvoRed\Framework\Support\Contracts\CartProductInterface::attributes(array $attributes)".

It doesn't seem to matter if product has or hasn't any attributes.

**Comment by indpurvesh** [comment]
@jamipietila feel like that Implementation of Interface is expecting some and but it returns different type of data.?

Does it happen with any (basic type) kind of product or variable product only? *** You can check the type in the backend. ****
