### ISSUE TITLE
Cant install 3.0.0 version

### ISSUE THREAD

**Issue by yoyoypy** [avored/laravel-ecommerce#382]
**Ideally we would expect you to raise a discussion on AvoRed Official Website **
https://www.avored.com/discussion/category/general

hey everyone, i tried to install 3.0.0 version but

```
$ composer create-project avored/laravel-ecommerce:3.0.0


  [InvalidArgumentException]
  Could not find package avored/laravel-ecommerce with version 3.0.0 in a version installable using your PHP version 7.1.18.

```
![php v](https://user-images.githubusercontent.com/55522331/65210908-2411bc80-dac7-11e9-921b-d4583f300ab1.jpg)
im using lastest xampp with php 7.3, do i have anything wrong?
looking for any help

thanks :)

**Comment by indpurvesh** [comment]
I have to fixed my `composer.json` file thanks will fix soon.

**Comment by yoyoypy** [comment]
thank you :)
waiting for fix now

**Comment by indpurvesh** [comment]
Right now `composer.json` contain

     "php": "^=7.2",              
       
In your wamp, if you switch to `php 7.2` in the meantime it should work.

**Comment by indpurvesh** [comment]
I did comit it into a dev branch once i will finished few more changes then will do a minor release soon in few days.

**Comment by yoyoypy** [comment]
i still having same error

`$ composer create-project avored/laravel-ecommerce:3.0.0


  [InvalidArgumentException]
  Could not find package avored/laravel-ecommerce with version 3.0.0 in a version installable using your PHP version 7.1.18.`

**Comment by indpurvesh** [comment]
you need `php 7.2`

**Comment by yoyoypy** [comment]
![wamp](https://user-images.githubusercontent.com/55522331/65212751-97b6c800-dacd-11e9-944e-7688bbaaa7be.jpg)
already using 7.2

**Comment by yoyoypy** [comment]
i have different version of php, i use 7.2 in apache but 7.1 in CLI.. so just reinstalled composer and fiola i can download avored again...

thanks @indpurvesh :)
