### ISSUE TITLE
Vue Component errors on registration page and menu group edit page

### ISSUE THREAD

**Issue by sagarthedev** [avored/laravel-ecommerce#388]
**Describe the bug**
I have just configured the project and got the following vue component error on the registration page

**Error**
![image](https://user-images.githubusercontent.com/53272767/65376040-13289d00-dcb9-11e9-9b34-fbe85b641562.png)
![image](https://user-images.githubusercontent.com/53272767/65376453-aa8fef00-dcbd-11e9-87db-fd01da886219.png)

**Comment by indpurvesh** [comment]
@sagarthedev 

 - 1 Register Page bug:  
      :`resources/views/auth/register.blade.php` just replace the tag in filed `<login-fields>`
 with `<register-fields inline-template>` same for ending tag too. (committed in dev branch)
 - 2 Menu Builder bug I have a feeling that its related to dynamic loading of the component. I have to dig bit deeper.
