### ISSUE TITLE
Payment button is missing on the shopping cart page

### ISSUE THREAD

**Issue by kguillaume** [avored/laravel-ecommerce#389]
I checked the demo online and found the same issue on my local website.
1 ) When you add an item to the cart, you don't have a button to pay and go checkout.
2) When you double click on the same article it generates an exception error. "ErrorException
array_key_exists (): The first argument should be a string or an integer "
3) On my local website the product images doesn't displayed.
I installed two different versions of avored 3.* I still have this issue.

- first avored composer file

        "php": "^7.1.3",
        "avored/framework": "3.*",

- second avored composer file

        "php": ">=7.2",
        "avored/framework": "^3.0"

I use mysql mariaBD 10.4.6 and PHP : 7.3.9

Sorry for my english

![FireShot Capture 021 - AvoRed - demo avored com](https://user-images.githubusercontent.com/27366521/65544395-a6a0de80-df02-11e9-87f2-02d179e60b4b.png)
![FireShot Capture 020 - 🧨 array_key_exists()_ The first argument should be either a string o_ - demo avored com](https://user-images.githubusercontent.com/27366521/65544450-c3d5ad00-df02-11e9-8be3-25228235b81d.png)

![FireShot Capture 022 - AvoRed - 127 0 0 1](https://user-images.githubusercontent.com/27366521/65545042-1c597a00-df04-11e9-9ae0-3e014575c3fd.png)

**Comment by indpurvesh** [comment]
@kguillaume 

 - 1 ) When you add an item to the cart, you don't have a button to pay and go checkout. (i will take a look at it today)

 - 2) When you double click on the same article it generates an exception error. "ErrorException
array_key_exists (): The first argument should be a string or an integer" (feel like its a bug.. i think i have to disabled button while request is in process so people cant click again..)
 -  
3) On my local website the product images doesn't displayed. (Solution please run the below command)

      php artisan storage:link

**Comment by kguillaume** [comment]
Good! Thanks.

**Comment by indpurvesh** [comment]
@kguillaume update on this issue.
 
all of the bug that you have mentioned here is fixed now. But it is in `dev` branch now. Once this and few other stuff is ready then i will add them to release stage. thanks @kguillaume
