### ISSUE TITLE
Missing autoload

### ISSUE THREAD

**Issue by james2doyle** [avored/laravel-ecommerce#390]
**Describe the bug**
A composer package cannot be found: `Class 'AvoRed\CashOnDelivery\Module' not found`

**To Reproduce**
1. Clone `master`
2. `composer install`
3. See error

**Screenshots**
<img width="1002" alt="Screen Shot 2019-09-29 at 11 41 54 AM" src="https://user-images.githubusercontent.com/1425304/65837592-2b4a7e80-e2ae-11e9-9135-5717cb7e6b9a.png">

**Additional context**
I think the reason is that the `modules` folder is not autoloaded properly. The error can be fixed with the following patch:

```diff
diff --git a/composer.json b/composer.json
index 55c37632..190cf475 100644
--- a/composer.json
+++ b/composer.json
@@ -34,7 +34,8 @@
     },
     "autoload": {
         "psr-4": {
-            "App\\": "app/"
+            "App\\": "app/",
+            "AvoRed\\": "modules/avored/"
         },
         "classmap": [
             "database/seeds",

```

**Comment by indpurvesh** [comment]
@james2doyle Make sure that you have file exist at these location.  `modules/avored/cash-on-delivery/src/Module.php`. 

Yes, i am setting the autoloading in programming so you don't have to add it into composer.json.

**Comment by james2doyle** [comment]
Yeah they exist. I cloned this yesterday from `master`. They autoloading seems to not be working at the moment unless set explicitly

**Comment by james2doyle** [comment]
If they files didn’t exist, my patch to `composer.json` wouldn’t have worked

**Comment by indpurvesh** [comment]
@james2doyle It is very interesting. I can't replicate the bug in my local.
If it happens with others too then there might be a bug in `Module/Manager.php` file. (This file is part of the framework)
