### ISSUE TITLE
Menu Builder

### ISSUE THREAD

**Issue by yoyoypy** [avored/laravel-ecommerce#391]
hi everyone,

i tried to edit main menu but menu builder dont show up.
how can we fix this?

im using 3.0.1 btw

thanks :)

![Screenshot_16](https://user-images.githubusercontent.com/55522331/66023110-5df8af00-e51a-11e9-9e5a-831fc8be896d.jpg)

**Comment by indpurvesh** [comment]
Seems like it's an error of Vue component. @yoyoypy i will take a look at it.

**Comment by indpurvesh** [comment]
@yoyoypy 
Just fixed the bug in `dev` branch.

**Comment by yoyoypy** [comment]
thanksss !
appreciate it...
