### ISSUE TITLE
Image Issue

### ISSUE THREAD

**Issue by yoyoypy** [avored/laravel-ecommerce#392]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**
Images cant show up, even in clean install..
i think because the app calling wrong path of images.. check this screenshot...

**Screenshots**
![Screenshot_17](https://user-images.githubusercontent.com/55522331/66105207-0c692680-e5e5-11e9-80e0-35c0bd9a9a0f.jpg)

![Screenshot_18](https://user-images.githubusercontent.com/55522331/66105210-0f641700-e5e5-11e9-8985-ae42754036d7.jpg)

**Desktop (please complete the following information):**
 - Version 3.0.1

**Comment by yoyoypy** [comment]
the actual path is storage\app\public\uploads\catalog

**Comment by kguillaume** [comment]
I run below command it is worked for me.

php artisan storage:link

**Comment by indpurvesh** [comment]
@kguillaume you are right.

@yoyoypy if you just do `php artisan storage:link` it will work.

In Next release I will execute these command into `php artisan avored:install`

**Comment by yoyoypy** [comment]
okay then thanks

sorry im new using laravel and artisan :))

**Comment by indpurvesh** [comment]
@yoyoypy If you stuck with Avored i would rather suggest checkout Laravel Docs it is built on top of the laravel framework so most the laravel docs will give you more ideas.
