### ISSUE TITLE
Role Permission Issue

### ISSUE THREAD

**Issue by yoyoypy** [avored/laravel-ecommerce#394]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**
i added sales staff with sales role, but when i login with sales account, this account still have access to system panel.

**Screenshots**
![Screenshot_21](https://user-images.githubusercontent.com/55522331/66187097-30446f00-e6ae-11e9-9883-976f6da4f4f6.jpg)
![Screenshot_22](https://user-images.githubusercontent.com/55522331/66187103-32a6c900-e6ae-11e9-93f8-a5cb2e419c8f.jpg)
![Screenshot_23](https://user-images.githubusercontent.com/55522331/66187105-34708c80-e6ae-11e9-963f-0c677772f919.jpg)

**Desktop (please complete the following information):**
 - Version 3.0.1

**Comment by indpurvesh** [comment]
I think it might be a bug with permission middleware not working properly. Will take a look at it soon

**Comment by yoyoypy** [comment]
looking forward to that, thanks :)

**Comment by indpurvesh** [comment]
It has been fixed in `dev` branch. thanks @yoyoypy
