### ISSUE TITLE
Clicking "Add to cart" for a product already in the cart redirects to an error page

### ISSUE THREAD

**Issue by medteck** [avored/laravel-ecommerce#396]
On a product page, when we click on "add to cart" for the first time, everything is ok. But when we click twice on the same button (which means the product was already in the cart), we get an error page saying "array_key_exists(): The first argument should be either a string or an integer".

This is a link to see the error we get : https://flareapp.io/share/A7E2WE5r#F49

Thanks

**Comment by indpurvesh** [comment]
@medteck I do remember fixing these bug few weeks ago. do you want to give it a try with `composer update` let me know if the problem still persist or not?

**Comment by medteck** [comment]
> @medteck I do remember fixing these bug few weeks ago. do you want to give it a try with `composer update` let me know if the problem still persist or not?

The same problem still remains after a `composer update`.

**Comment by indpurvesh** [comment]
i just did a minor release. Can you try `composer update` and let me know if the bug still exist or not?
