### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by uswakamili** [avored/laravel-ecommerce#398]
![screensht](https://user-images.githubusercontent.com/14214449/66906491-7c79a280-f010-11e9-9bba-a5f1a7abcbb2.jpg)
 Please help with this issue

**Comment by yoyoypy** [comment]
try to run `php artisan storage:link`

**Comment by uswakamili** [comment]
Thanks what about adding a new payment gateway?

**Comment by uswakamili** [comment]
ErrorException
array_key_exists(): The first argument should be either a string or an integer
http://localhost:8000/add-to-cart

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
:1279
C:\Users\Web\laravel-ecommerce\vendor\laravel\framework\src\Illuminate\Support\Collection.php:1279



     * @return \Illuminate\Support\Collection

     */

    public function toBase()

    {

        return new self($this);

    }

 

    /**

     * Determine if an item exists at an offset.

     *

     * @param  mixed  $key

     * @return bool

     */

    public function offsetExists($key)

    {

        return array_key_exists($key, $this->items);

    }

 

    /**

     * Get an item at a given offset.

     *

     * @param  mixed  $key

     * @return mixed

     */

    public function offsetGet($key)

    {

        return $this->items[$key];

    }

 

    /**

     * Set the item at a given offset.

**Comment by indpurvesh** [comment]
@uswakamili I am not sure why you having the same bug too. I can't replicate this bug now. I have fixed these `array_key_exists ` bug.

**Comment by indpurvesh** [comment]
Try `composer update` it should fixed the big.

**Comment by yoyoypy** [comment]
> Try `composer update` it should fixed the big.

tried this solution and solved

**Comment by yoyoypy** [comment]
when uploaded to shared hosting, its become problem too.
images not showing even tough the path is correct.
![Screenshot_57](https://user-images.githubusercontent.com/55522331/67837254-3a2c8700-fb21-11e9-8ede-5985b8b60422.jpg)

i tried to run `php artisan storage:link` terminal in host but its showing `The "public/storage" directory already exists.`

**Comment by indpurvesh** [comment]
Try with an absolute URL?
use `asset('storage/abc.jpg')`

**Comment by yoyoypy** [comment]
> Try with an absolute URL?
> use `asset('storage/abc.jpg')`

is that any permission issue?
where to change absolute URL?

**Comment by indpurvesh** [comment]
There is possibility. But if there is no permission then it should not load css and JavaScript too.

**Comment by indpurvesh** [comment]
Can you make sure that image file exist inside storage/app/public/upload folder. 

I have a feeling that you image don’t exist in that folder for some reason.

**Comment by yoyoypy** [comment]
> Can you make sure that image file exist inside storage/app/public/upload folder.
> 
> I have a feeling that you image don’t exist in that folder for some reason.

it exist
![Screenshot_58](https://user-images.githubusercontent.com/55522331/68098689-babc0080-fef0-11e9-8c36-f9217c10f7a8.jpg)

**Comment by yoyoypy** [comment]
do you want FTP access to my server?

**Comment by indpurvesh** [comment]
File path looks right to me.  Can you asked your web hosting company about the symbolic link between those folders??

Link should be

‘Public/storage => storage/app/public’

**Comment by yoyoypy** [comment]
i try to make symlink, but its failed..

![Screenshot_59](https://user-images.githubusercontent.com/55522331/68099830-49338080-fef7-11e9-95ba-2130ac19a8c9.jpg)
