### ISSUE TITLE
account-navbar issue

### ISSUE THREAD

**Issue by yoyoypy** [avored/laravel-ecommerce#399]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**
when customer login, then go to account page i got this error.

**Screenshots**
![Screenshot_37](https://user-images.githubusercontent.com/55522331/66909425-f1f86980-f036-11e9-9ccf-295e732f65ad.jpg)
![Screenshot_38](https://user-images.githubusercontent.com/55522331/66909430-f3c22d00-f036-11e9-9b9f-ed39a78d1607.jpg)

**Desktop (please complete the following information):**
- Version 3.0.0

**Comment by indpurvesh** [comment]
Try `$user->name` and `$user->image` and these variable comes from view composer file which you will find here `App\Http\Composers\NavComposer.php`

**Comment by yoyoypy** [comment]
boom it sloved...
thanks man !

**Comment by yoyoypy** [comment]
i got this issue again

![Screenshot_51](https://user-images.githubusercontent.com/55522331/67450807-c7b33700-f648-11e9-8021-fb22d7e9e742.jpg)
![Screenshot_52](https://user-images.githubusercontent.com/55522331/67450810-ca159100-f648-11e9-908b-85c6bc7d49de.jpg)

**Comment by indpurvesh** [comment]
Check this file `App\Http\Composers\NavComposer.php` which set up the user. 

I would open the method and do `dd($user)` in `compose method of NavComposer file`
