### ISSUE TITLE
Drop Item in Checkout and Cart Page

### ISSUE THREAD

**Issue by yoyoypy** [avored/laravel-ecommerce#400]
**Ideally we would expect you to raise a feature request on AvoRed Official Website **
https://www.avored.com/discussion/category/feature

Drop item button or check box for multi selected item in cart information at cart page and checkout page, because user will confuse if they want to cancel an item.

![Screenshot_39](https://user-images.githubusercontent.com/55522331/66975970-5ca6b500-f0ca-11e9-990a-585e8223f586.jpg)

and there is weird condition i recenly replacing usd with local currency but in check out page still showing usd instead local currency. in homepage showing local currency.

![Screenshot_40](https://user-images.githubusercontent.com/55522331/66976046-a8595e80-f0ca-11e9-8bc9-207645e4b38a.jpg)

**Comment by indpurvesh** [comment]
Feature request . Will add these features soon.

**Comment by yoyoypy** [comment]
cool man :)

**Comment by indpurvesh** [comment]
@yoyoypy Cart Update and Delete feature has been added but its in `dev`  branch in the next cycle is will be released.

**Comment by indpurvesh** [comment]
Do you have a `dev` branch for both? `framework` and  `https://github.com/avored/laravel-ecommerce/tree/dev`

**Comment by yoyoypy** [comment]
im using `dev` branch for my avored.. not `master` branch...
