### ISSUE TITLE
Class AvoRed\Framework\System\Controllers\AdminUserController does not exist

### ISSUE THREAD

**Issue by rylxes** [avored/laravel-ecommerce#401]
when i try to get my route list, ... i get this error 

 Target class [AvoRed\Framework\System\Controllers\AdminUserController] does not exist.

**Comment by indpurvesh** [comment]
Bug is fixed in dev branch so in next release it will be available.

If you want to do a simple fixed Solution is:

change the `vendor/avored/framework/routes/web.php` 

     Route::post('admin-user-image', [\AvoRed\Framework\User\Controllers\AdminUserController::class, 'upload'])
            ->name('admin-user-image-upload');
