### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by rylxes** [avored/laravel-ecommerce#402]
A fresh installation of the application keeps giving me `Illegal offset type in isset or empty` when i visit the admin url 

the error message :  https://flareapp.io/share/Rmrqpb5z#F41

#159

**Comment by indpurvesh** [comment]
TRY these command 

     composer create-project avored/laravel-ecommerce folder_name --prefer-dist 3.0.1

**Comment by rylxes** [comment]
this does not still work , ... i have found a fix for it , ... the issue is from avored/framework
... can i create a pull request ?

**Comment by indpurvesh** [comment]
Yes you can do a PR on `framework`
