### ISSUE TITLE
is there is no table or my seed goes rong?

### ISSUE THREAD

**Issue by Adamkaram** [avored/laravel-ecommerce#407]
![Screenshot 2019-11-10 18 51 26](https://user-images.githubusercontent.com/52092726/68543563-33d4bf80-03eb-11ea-9fbf-c62a2fd62007.png)

**Comment by yoyoypy** [comment]
check in your sql if there is wishlist table..
if none you can do migration
![Screenshot_72](https://user-images.githubusercontent.com/55522331/68836246-7dbfed00-06ec-11ea-909f-cb9238511f96.jpg)

**Comment by indpurvesh** [comment]
@Adamkaram Sorry for late reply.

I have fixed that bug in dev branch but its not release yet.

How to fix: 

 Open a file at `modules/avored/wishlist/src/Module.php@registerResources` and add a below line in that method.

    protected function registerResources()
    {
          $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');
          $this->loadTranslationsFrom(__DIR__ . '/../resources/lang', 'a-wishlist');
          $this->loadMigrationsFrom(__DIR__ . '/../database/migrations'); // Uncomment or Add  this line
    }
