### ISSUE TITLE
Orders doesnt show anything in account side

### ISSUE THREAD

**Issue by onir272** [avored/laravel-ecommerce#415]
I encountered following error.I tried clean install two times

`app.js:40236 [Vue warn]: Unknown custom element: <a-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <UserOrderTable> at resources/components/account/order/OrderTable.vue <ACol>
         <ARow>
           <Anonymous>
             <ALayoutContent>
               <Anonymous>
                 <ALayout>
                   <Anonymous>
                     <ALayoutContent>
                       <Anonymous>
                         <ALayout>
                           <AvoredLayout> at resources/components/layout/Layout.vue
                             <Root>`

**Comment by indpurvesh** [comment]
@onir272 have fixed the bug in `dev` branch.  thanks for raising the issue.
