### ISSUE TITLE
Shopping cart does not refresh when deleting an item.

### ISSUE THREAD

**Issue by tonyanant** [avored/laravel-ecommerce#416]
When deleting items from the shopping cart it does not refresh automatically and the deleted item remains there until manually refreshing.

**To Reproduce**
1. Add an item to shopping cart
2. Delete item
3. Refresh

I can try to solve this if it's ok with you :)

**Comment by indpurvesh** [comment]
Bug has been fixed in `dev` branch. thanks @tonyanant for raising the bug.

**Comment by tonyanant** [comment]
No problem!
