### ISSUE TITLE
Installation wizard doesn't recognize database credentials

### ISSUE THREAD

**Issue by luissanchez0305** [avored/laravel-ecommerce#421]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**

**To Reproduce**
Last step of installation wizard, after putting all the .env settings and the right of 2 databases credentials I get the error/1045 of database credentials
Install button of last step of installation wizard

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by indpurvesh** [comment]
@luissanchez0305 can you share a screenshot or an error or something? 

To me it seems like it's something to do with in valid database credential. If you have just updated the database password or something then please restart the server.

**Comment by luissanchez0305** [comment]
Is the standard screen that state that I'm putting the wrong database credentials. 

But I'm sure I'm putting the right one that I've used since always (so no restart needed). I did try with another server and another database and still doesn't recognize my database. Any ideas?
