### ISSUE TITLE
Moduel :: Banner ::  no find doc ,  How to use it.

### ISSUE THREAD

**Issue by marol1210** [avored/laravel-ecommerce#422]
**Ideally we would expect you to raise a discussion on AvoRed Official Website **
https://www.avored.com/discussion/category/general

use admin account  entry Avored background , and , 
it's redirect to main page when click banner menu

![image](https://user-images.githubusercontent.com/7519301/80700063-a5c2d180-8b0f-11ea-9da4-4e9fb441ed86.png)

**Comment by marol1210** [comment]
view the source ,  this module , use default auth middleware 'web',   
How to understand this design

> Route::middleware(['web', 'admin.auth'])
>     ->prefix($baseAdminUrl)
>     ->name('admin.')
>     ->group(function () {
>         Route::get('banner', AvoRed\Banner\Http\Controllers\TableController::class)
>             ->name('banner.table');
>         Route::get(
>             'banner-edit/{banner?}',
>             AvoRed\Banner\Http\Controllers\EditController::class
>         )->name('banner.edit');
>         Route::post(
>             'banner-save/{banner?}',
>             AvoRed\Banner\Http\Controllers\SaveController::class
>         )->name('banner.save');
>         Route::delete('banner/{banner}', AvoRed\Banner\Http\Controllers\DestroyController::class)
>             ->name('banner.destroy');
>         Route::post('banner-upload', AvoRed\Banner\Http\Controllers\UploadController::class)
>             ->name('banner.upload');
>     });

![image](https://user-images.githubusercontent.com/7519301/80700311-0fdb7680-8b10-11ea-9254-19b634984f8a.png)

**Comment by indpurvesh** [comment]
@marol1210 

To me seems like i am missing adding `permission` middleware which check if the user has the permission to see the admin banner page. This middleware apply only for admin routes only.

**Comment by marol1210** [comment]
thanks 
I get it.

**Comment by marol1210** [comment]
@indpurvesh 
I can't  learn the Views by doc  from official website , only by view source code ,  because there is something wrong in the view page.  very grateful for your help!

![image](https://user-images.githubusercontent.com/7519301/81131271-30c32200-8f7d-11ea-951d-8fc2d33262a1.png)

**Comment by SilverFoxA** [comment]
Change the middleware from this `'web', 'admin.auth'`  to `'web', 'admin.auth:admin', 'permission'` in the banner module route file.
