### ISSUE TITLE
Blank Screens both on the home and admin sides after installation

### ISSUE THREAD

**Issue by mbbaraka** [avored/laravel-ecommerce#436]
I've just installation the app very well and would like to start development when I run in in the browser nothing is displayed  page sources exist. I m confused by the app tags. Such as a-breadcrumb-item, product-card, a-col etc. What do they mean and how can I make the app work for me?

Thanks in advance

**Comment by indpurvesh** [comment]
Yes I know I have made an mistake with that version so re installed it again you will get admin panel working. 

Front end part is still has some error. Hopefully to fixed it soon. 

Tag that you talking about it’s more like a vie component. 
For example check this file 
https://github.com/avored/framework/blob/master/resources/components/system/forms/AvoRedInput.vue

**Comment by mbbaraka** [comment]
Thanks so much @indpurvesh for the quick response. Let me reinstall it again and start working with the admin side. But can I easily use it without involving the Vue stuff? Honestly I'm not familiar with it. 
Thanks once again

**Comment by indpurvesh** [comment]
Try next version it should be fixed.
