### ISSUE TITLE
javascript is something wrong

### ISSUE THREAD

**Issue by marol1210** [avored/laravel-ecommerce#441]
**Describe the bug**
javascript is wrong , make page not work perfect.

**To Reproduce**
1. pull  latest  branch , master.
2. composer update
3. npm run dev ,  there is a question to me.  in  root of project,  i saw webpack.mix.js  source  code  **mix.js('packages/framework/....')** ,  but  i can't find  **packages/framework** directory, result npm run fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/7519301/85493003-af951c80-b608-11ea-9bcb-71161e6bef62.png)

![image](https://user-images.githubusercontent.com/7519301/85493143-eec36d80-b608-11ea-9990-e9cccb3567bc.png)

**Desktop (please complete the following information):**
 - Browser :  Microsoft Edge
 - Version  :  83.0.478.37

**Comment by marol1210** [comment]
1. delete public/avored-admin/**

2. page was ok that there is no js error when exec  follow command ,   but  there is something about css style issue;

> php artisan vendor:publish --provider="AvoRed\Framework\AvoRedProvider"
> Copied Directory [/vendor/avored/framework/assets/avored-admin] To [/public/avored-admin]
> Publishing complete.

![image](https://user-images.githubusercontent.com/7519301/85986969-91238c80-ba1f-11ea-9fef-355ea07f7a32.png)

**Comment by indpurvesh** [comment]
Sorry I am just trying to understand that what is the problem? Is it that dashboard is in English?

**Comment by marol1210** [comment]
@indpurvesh 

thanks ,  you appear

it's not problem about dashboard in English or page language.   

**problem**:
i pulled  latest branch master,   install avored local,  and fail to open site,  because some javascript error  and the page style is different with previous.  first , i think there is something wrong with local environment . so i try to rebuild font-end resource use npm & lavavel_mix(webpack),  but failed. 

Now,  i continue learn code  and one question  about  avored's  fronted, thanks for your help.
   

- avored  utilize ant-vue  in  admin background & front ,  how  separate  fronted resource between background & front?

 
   (_follow snapshot  perplex me, this is problem to me all the time,  it's  reason that i exec `npm run dev` to hope fixed_)

normal  page:
![image](https://user-images.githubusercontent.com/7519301/86202102-eb455e80-bb93-11ea-9b7b-27b6dabf5714.png)

error page:
![image](https://user-images.githubusercontent.com/7519301/86202253-568f3080-bb94-11ea-822a-8a5b4704a493.png)





> Sorry I am just trying to understand that what is the problem? Is it that dashboard is in English?

**Comment by marol1210** [comment]
[https://github.com/avored/laravel-ecommerce/issues/442#issuecomment-655160577](url)
