### ISSUE TITLE
Blank Home page After fresh installation

### ISSUE THREAD

**Issue by yaxirhuxxain** [avored/laravel-ecommerce#442]
First I would like to thank all the developers for their time and efforts. Adored is a great commerce framework.

I have recently installed a fresh version of avored without having any issues. I was able to run my server (php artisan serve) and can browse admin panel without any issues (127.0.0.1:8000/admin) but when I try to browse the home page (frontend) it shows a blank page.

After inspecting the console I found it have some issues with VueJS framework.

`DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/js/performance-now.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
app.js:129 GET http://127.0.0.1:8000/js/chunk/23.js net::ERR_ABORTED 404 (Not Found)
requireEnsure @ app.js:129
(anonymous) @ app.js:76740
resolveAsyncComponent @ app.js:68090
createComponent @ app.js:67608
_createElement @ app.js:67829
createElement @ app.js:67761
vm._c @ app.js:67898
eval @ VM215:3
Vue._render @ app.js:67952
updateComponent @ app.js:68468
get @ app.js:68879
Watcher @ app.js:68868
mountComponent @ app.js:68475
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:73445
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:76345
Vue._init @ app.js:69413
Vue @ app.js:69479
./resources/js/app.js @ app.js:76751
__webpack_require__ @ app.js:64
0 @ app.js:76795
__webpack_require__ @ app.js:64
(anonymous) @ app.js:199
(anonymous) @ app.js:202
app.js:73465 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
app.js:65035 [Vue warn]: Failed to resolve async component: function () {
  return __webpack_require__.e(/*! import() */ 23).then(__webpack_require__.bind(null, /*! ../components/layout/Layout.vue */ "./resources/components/layout/Layout.vue"));
}
Reason: ChunkLoadError: Loading chunk 23 failed.
(error: http://127.0.0.1:8000/js/chunk/23.js)
warn @ app.js:65035
(anonymous) @ app.js:68080
(anonymous) @ app.js:64752
Promise.then (async)
resolveAsyncComponent @ app.js:68096
createComponent @ app.js:67608
_createElement @ app.js:67829
createElement @ app.js:67761
vm._c @ app.js:67898
eval @ VM215:3
Vue._render @ app.js:67952
updateComponent @ app.js:68468
get @ app.js:68879
Watcher @ app.js:68868
mountComponent @ app.js:68475
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:73445
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js:76345
Vue._init @ app.js:69413
Vue @ app.js:69479
./resources/js/app.js @ app.js:76751
__webpack_require__ @ app.js:64
0 @ app.js:76795
__webpack_require__ @ app.js:64
(anonymous) @ app.js:199
(anonymous) @ app.js:202`

I have tried to resolve the issues by recompiling the js files (npm run dev) but same result.

Can anyone help me in this regard? Thanks in advance.

**Comment by indpurvesh** [comment]
To me it seems like it’s an issue with dynamic loading of an vue component. I think in next release I have to remove this Laravel mix dynamic loading.

**Comment by marol1210** [comment]
@yaxirhuxxain 
debug and find ,  it is  config problem of laravel_mix .   i solved it.   exce twice 'npm run dev'.    following step

1. first , comment start from  /******** AVORED ADMIN JS  **********/  to end  ,  exec npm run dev,  this will  pack exclude AVORED ADMIN part

2. second ,  comment  the others  except  AVORED ADMIN part (opposite step 1)  and modify  laravel-ecommerce/webpack.mix.js 

> /******** AVORED ADMIN JS  **********/
> //let publicPath = 'public/avored-admin'  //add , required
> //mix.setPublicPath(publicPath)               //add , required
> mix.js('/Users/mma/git/laravel-ecommerce/vendor/avored/framework/resources/js/app.js', REMAIN others)
> mix.less('/Users/mma/git/laravel-ecommerce/vendor/avored/framework/resources/less/app.less', REMAIN others) ;

excited! 

![image](https://user-images.githubusercontent.com/7519301/86888175-55c64380-c12c-11ea-9ea8-9f9cfbf6e408.png)
