### ISSUE TITLE
Laravel Dusk setup for Framework

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#453]
- [ ] Install Laravel Dusk Orchestra Packae
 - [ ] Set up a basic unit test

**Comment by chandresh1339** [comment]
Please can I work on this request?

**Comment by indpurvesh** [comment]
@chandresh1339 

Sure you can work on Dusk testing anytime. Ideally i would like to do a Dusk test for the Admin Package. If you can do that will be so great but still if you can add the Dusk test on basic test that will be fine.
AvoRed framework If you can set up the https://github.com/orchestral/testbench-dusk will be great.
https://github.com/avored/framework

**Comment by chandresh1339** [comment]
Thanks. I will work on it.

**Comment by indpurvesh** [comment]
@chandresh1339 
Thanks

**Comment by chandresh1339** [comment]
Kindly check the proposed changes.
