### ISSUE TITLE
php artisan avored:admin:make is not working

### ISSUE THREAD

**Issue by mobarokhossen** [avored/laravel-ecommerce#463]
**Ideally we would expect you to raise a bug on AvoRed Official Website **
https://www.avored.com/discussion/category/general

**Describe the bug**
php artisan avored:admin:make is not working
Admin can't find role. 
please check the screenshot.
![2020-08-20](https://user-images.githubusercontent.com/17096134/90740164-ab2b6e00-e2f0-11ea-838b-80e5c50f1f5f.png)

**Comment by indpurvesh** [comment]
Try it with sample data to yes. It should work. I will move out the Admin role create command outside of demo data.

**Comment by indpurvesh** [comment]
This bug should be fixed too. Just a note that once you finished the installation via composer make sure you run the `php artisan avored:install` command
