### ISSUE TITLE
Return value of AvoRed\Framework\Database\Repository\CurrencyRepository::getDefault() must be an instance of AvoRed\Framework\Database\Models\Currency, null returned

### ISSUE THREAD

**Issue by herd-design** [avored/laravel-ecommerce#464]
Hai, after I installed the avored, and try to run the homepage it shows error message:
Return value of AvoRed\Framework\Database\Repository\CurrencyRepository::getDefault() must be an instance of AvoRed\Framework\Database\Models\Currency, null returned

I have already follow all the installation step from http://avored.com/docs/user/installation.
before installation, I have already update my composer too.

here the screenshot:
![image](https://user-images.githubusercontent.com/63194593/90945400-d7f59780-e44e-11ea-8acd-69c1e1f1756d.png)
![image](https://user-images.githubusercontent.com/63194593/90945413-f9568380-e44e-11ea-8024-e66ecaf7c0ad.png)

I used:
- Chrome Browser ver. 84.0.4147.135 
- windows 10

**Comment by indpurvesh** [comment]
This bug should be fixed in the new release too and make sure you install the AvoRed with the `php artisan avored:install` command
