### ISSUE TITLE
New user registration password did not encrypt

### ISSUE THREAD

**Issue by shern91** [avored/laravel-ecommerce#471]
I have install avored framework and have been tested some function. I found a small bug is when I registered a new user (Customer), after i logout I not able to login again, the error said 'These credentials do not match our records'. After I searched for my database, i realized the customer table, in password field, the password is storing as plain text and did not encrypt.

In App\Http\Controllers\Auth\RegisterController, in function create, the code look is

`protected function create(array $data)
{
        return Customer::create([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'email' => $data['email'],
            'password' => $data['password'],
        ]);
}
`

I think the code should be change to 

`protected function create(array $data)
{
        return Customer::create([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'email' => $data['email'],
            'password' =>  bcrypt($data['password']),
        ]);
}`

**Comment by indpurvesh** [comment]
@shern91 I did notice that few days ago too. It has been fixed in new release.

checkout this `https://github.com/avored/laravel-ecommerce/blob/master/app/Http/Controllers/Auth/RegisterController.php#L80`
