### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by CodeCures** [avored/laravel-ecommerce#472]
The installtion was great though i got composer memory limit error which i got fixed by running COMPOSER_MEMORY_LIMIT=-1 composer update and anything aside that was just fine but when i run php artisan serve and visit http://127.0.0.1:8000/admin/
i get this error
![https://content.screencast.com/users/couragesblog/folders/Default/media/0d0a2a9b-4593-4e69-b5ff-5daddce37417/avored.JPG](https://content.screencast.com/users/couragesblog/folders/Default/media/0d0a2a9b-4593-4e69-b5ff-5daddce37417/avored.JPG)
 i really dont know why this is coming up but i could only hope to get help from you guys

**Comment by indpurvesh** [comment]
@CodeCures 

Have you execute php artisan scored:install command? 

That command will create a required currency record in database.

**Comment by CodeCures** [comment]
@indpurvesh 
yea, have done that, still wont work

**Comment by indpurvesh** [comment]
@CodeCures 
Ideally it should create an currency record but seems likes it’s not creating that dB record. I try to replicate it into my local and fixed the big. Thank for raising the bug.

**Comment by CodeCures** [comment]
@indpurvesh 
you are welcome, but still haven't got a solution. do i need to run a fresh installation or what is exactly is the solution to this?

**Comment by athik13** [comment]
I am also having the same issue

**Comment by indpurvesh** [comment]
@athik13 @CodeCures 

I have fixed the bug in my local Repository. I will commit and release the new version soon. 

Bug was in configuration database table which was missing the record of default_currency.

**Comment by walidos04** [comment]
Same issue here

**Comment by indpurvesh** [comment]
@walidos04 @athik13 @CodeCures 

I have fixed the bug and did a minor release. Try it with `composer update` then `php artisan avored:install` after both of these command bug should be fixed.

Thanks to all
