### ISSUE TITLE
Package discovery error when installing in production mode

### ISSUE THREAD

**Issue by adwiv** [avored/laravel-ecommerce#475]
**Describe the bug**
When installed in production mode with --no-dev, composer gives an error regarding missing class

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Application.php line 679:
                                                       
  Class 'Barryvdh\Debugbar\ServiceProvider' not found  
                                                       

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**To Reproduce**
Create a fresh install with `composer create-project --prefer-dist --no-dev avored/laravel-ecommerce`
or simply run `composer update --no-dev` in existing project

**Desktop (please complete the following information):**
 - Browser N/A
 - Version 3.1.4
 - Laravel v6.18.40

**Additional context**
The issue can be traced to file `app/Providers/AppServiceProvider.php` Line 23 to 38. Removing these lines fixes the issue.

https://github.com/avored/laravel-ecommerce/blob/6e9a224e1c6ba6a08ea411424d7d8a1ccbfa0ab4/app/Providers/AppServiceProvider.php#L23-L38

**Comment by indpurvesh** [comment]
If you change your `APP_ENV= production`  into `.env` file it should fixed it.
