### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by marqusG** [avored/laravel-ecommerce#476]
Hello.
I just want let you know 1 issues I have found: trying to take a look at the live demo I've got an error with database connection:
Illuminate\Database\QueryException
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from `configurations` where `code` = default_currency limit 1)

Hope this help you
Cheers

**Comment by indpurvesh** [comment]
@marqusG 

It's been fixed.

**Comment by marqusG** [comment]
Fantastic, thank you! I'll try the demo.
