### ISSUE TITLE
Category edit not working

### ISSUE THREAD

**Issue by RaHanja** [avored/laravel-ecommerce#483]
I have an error with my new installation of avored
[Vue warn]: Error compiling template:

Inline-template components must have exactly one child element.
<category-save base-url="http://127.0.0.1:8000/admin" :category="{&quot;id&quot;:1,&quot;name&quot;:&quot;test&quot;,&quot;slug&quot;:&quot;test&quot;,&quot;meta_title&quot;:&quot;test&quot;,&quot;meta_description&quot;:&quot;tetst&quot;,&quot;created_at&quot;:&quot;2020-09-30 13:23:02&quot;,&quot;updated_at&quot;:&quot;2020-09-30 13:23:02&quot;}" inline-template="">x
  
avored.js:1194 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <CategorySave> at resources/components/catalog/category/CategorySave.vue
       <AvoredLayout> at resources/components/system/Layout.vue
         <Root>

**Comment by indpurvesh** [comment]
@RaHanja i will check it out the bug seems simple to fixed

**Comment by RaHanja** [comment]
@indpurvesh Thank you
