### ISSUE TITLE
Product Images Save: Raise Exception

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#487]
While in AvoRed Admin in Product edit/save screen.

when we try to upload multiple image at the same time then click in some cases it raise the exception.

**Comment by paresh27** [comment]
@indpurvesh , I would like to work on this.

**Comment by indpurvesh** [comment]
@paresh27 

Surely. You can take this assign. Bug is in this file `https://github.com/avored/framework/blob/master/src/Catalog/Controllers/ProductController.php@ saveProductImages` 
You have to fork this repository `https://github.com/avored/framework`. 

Let me know if you need any help.

**Comment by AlexMalikov94** [comment]
@indpurvesh  https://github.com/avored/framework/pull/141

**Comment by indpurvesh** [comment]
This bug is fixed in `developed` branch.
