### ISSUE TITLE
Vue 3 upgrade

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#492]
We need to upgrade all the backend and front end component including `avored-components` upgrade to Vue3.

**Comment by lhsazevedo** [comment]
Are Vue Router or Vuex being used? I think they aren't ready for v3 right now, but should be soon

**Comment by indpurvesh** [comment]
@lhsazevedo 

I have seen them. I think they have a beta version available now with Vue3.

Only the main problem is that have to upgrade all the component to vue3 which would be a hugh task.
