### ISSUE TITLE
Laravel 8 Upgrade to avored/framework

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#493]
Upgrade to use laravel 8 ideally it should be on `avored/framework` 
  - [x] Upgrade Framework
  - [ ] Upgrade App

**Comment by JunaidJaved8461** [comment]
@indpurvesh  I want to contribute in it!! You want to upgrade this project into Laravel 8 Right?

**Comment by indpurvesh** [comment]
@JunaidJaved8461 

sure you can work on it if you like to help in the upgrade.

Ideally you should upgrade the [framework](https://www.github.com/avored/framework)  repository.

**Comment by indpurvesh** [comment]
@JunaidJaved8461 


Can you please do a PR again on `developed` with that laravel8 upgrade. By mistake i click `close  & comment` instead of `comment` only.

**Comment by indpurvesh** [comment]
@JunaidJaved8461 

If you want to continue with upgrading the app part as well. Let me know if you need any help
