### ISSUE TITLE
Column not found: 1054 Unknown 'url' field in field list"

### ISSUE THREAD

**Issue by olivsinz** [avored/laravel-ecommerce#495]
**Describe the bug**
$ php artisan avored:install
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_000000_create_users_table (0.06 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated: 2014_10_12_100000_create_password_resets_table (0.06 seconds)
Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated: 2016_06_01_000001_create_oauth_auth_codes_table (0.09 seconds)
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated: 2016_06_01_000002_create_oauth_access_tokens_table (0.11 seconds)
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated: 2016_06_01_000003_create_oauth_refresh_tokens_table (0.1 seconds)
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated: 2016_06_01_000004_create_oauth_clients_table (0.06 seconds)
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated: 2016_06_01_000005_create_oauth_personal_access_clients_table (0.03 seconds)
Migrating: 2017_03_29_000000_avored_framework_schema
Migrated: 2017_03_29_000000_avored_framework_schema (3.72 seconds)
Migrating: 2017_03_29_000000_avored_framework_schema_3_1_3
Migrated: 2017_03_29_000000_avored_framework_schema_3_1_3 (0.25 seconds)
Migrating: 2017_03_29_000000_avored_framework_schema_3_1_5
Migrated: 2017_03_29_000000_avored_framework_schema_3_1_5 (0.07 seconds)
Migrating: 2017_03_29_000001_avored_review_schema
Migrated: 2017_03_29_000001_avored_review_schema (0.07 seconds)
Migrating: 2017_03_29_000001_avored_wishlist_schema
Migrated: 2017_03_29_000001_avored_wishlist_schema (0.07 seconds)
Migrating: 2019_09_21_003425_alter_user_table
Migrated: 2019_09_21_003425_alter_user_table (0.05 seconds)
The "public/storage" directory already exists.

Would you like to install Dummy Data? (yes/no) [no]:
> yes

Copied Directory [\modules\avored\demodata\assets\uploads] To [\storage\app\public\uploads]
Publishing complete.
Migrating: 2017_03_29_000000_avored_demo_data_schema

Illuminate\Database\QueryException : SQLSTATE[42S22]: Column not found: 1054 Unknown 'url' field in field list (SQL: insert into `menus` (`name`, `url`, `menu_group_id`, `updated_at`, `created_at`) values (AvoRed, /category/avored, 1, 2020-10-07 10:33:49, 2020-10-07 10:33:49)) at ~\code\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
665| // If an exception occurs when attempting to run a query, we'll format the error
666| // message to include the bindings with SQL, which will make this exception a
667| // lot more helpful to the developer instead of just the database's errors.
668| catch (Exception $e) {
> 669| throw new QueryException(
670| $query, $this->prepareBindings($bindings), $e
671| );
672| }
673|

Exception trace:

1 Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42S22]: Column not found: 1054
Unknown 'url' field in field list")
~\code\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\
PDO\Exception.php:18

2 Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException)) ~\code\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:82

Please use the argument -v to see more details.

**To Reproduce**
1. ``composer create-project --prefer-dist avored/laravel-ecommerce``
2. Set up your Envirionment(.env) file
3. ``php artisan avored:install``

**Comment by indpurvesh** [comment]
@0l1v3r5 

Try again with `composer create-project --prefer-dist avored/laravel-ecommerce avored`

then follow the steps as you did again with fresh installation it should work.

**Comment by 0l1v3r5** [comment]
I just tried again as you said and I encountered the same problem

**Comment by indpurvesh** [comment]
@0l1v3r5 

It's very odd to see you seeing that issue. I will do more debugging about it and try to replicate.

This is the file which runs when installing the demo data.

[https://github.com/avored/laravel-ecommerce/blob/master/modules/avored/demodata/database/migrations/2017_03_29_000000_avored_demo_data_schema.php#L374](https://github.com/avored/laravel-ecommerce/blob/master/modules/avored/demodata/database/migrations/2017_03_29_000000_avored_demo_data_schema.php#L374)

As you can see all those menu doesn't contain any url as a field parameter data. So not sure why it's happening in yours.  If you want you can copy the file data and put them into your file then try again. If issue still persist it mean something must be wrong somewhere.

**Comment by luckys383** [comment]
@0l1v3r5 I' checking your mentioned issue. In one of your Framework migration, `url` column is deleted from your menus table. That's why you are facing this issue? When I removed that line of code then it is working fine. Below is the migration link, kindly check and let me know if I can help you on this?

https://github.com/avored/framework/blob/master/database/migrations/2017_03_29_000000_avored_framework_schema_3_1_5.php#L18

**Comment by indpurvesh** [comment]
@luckys383 

I know in past i was using a url that has changes to `route_info` 

thanks now i get the idea. will fixed it soon.

**Comment by 0l1v3r5** [comment]
thank you all. I found it yesterday and fixed in my end.

**Comment by indpurvesh** [comment]
If you want you can do a PR and with if you are registered with hacktoberfest and do 4 PR in October then they send you a t shirt and gifts.

**Comment by 0l1v3r5** [comment]
Cool ! Why not ? I've got it...

**Comment by indpurvesh** [comment]
@0l1v3r5 You have to sign up to hacktoberfest.

**Comment by AlexMalikov94** [comment]
@indpurvesh  There is an error with the need to merge from developed to master. But manually you can do it ```/vendor/avored/framework/src/Models/Menu.php``` and paste under the model this code. 
``` const CATEGORY = 'CATEGORY';
    const FRONT_MENU = 'FRONT_MENU';
    const CUSTOM = 'CUSTOM';
    const MENU_TYPE_OPTIONS = [
        self::CATEGORY => 'Category',
        self::FRONT_MENU => 'Front Menu',
        self::CUSTOM => 'Custom',
    ];
```

**Comment by indpurvesh** [comment]
@0l1v3r5 

Signup on this website. When you do a valid 4 PR in the month of an October then they give you a t-shirt and stickers. It applies to any open source project.

https://hacktoberfest.digitalocean.com/

**Comment by 0l1v3r5** [comment]
Ok I got it. Thanks.

**Comment by 0l1v3r5** [comment]
Could you please close the fixed issues so that we know what really remains to be fixed? The last time I created a Pull request before realizing that the issue was already fixed. Thanks for your amazing work. I really appreciate.

> 
> 
> @0l1v3r5
> 
> Signup on this website. When you do a valid 4 PR in the month of an October then they give you a t-shirt and stickers. It applies to any open source project.
> 
> https://hacktoberfest.digitalocean.com/
