### ISSUE TITLE
ErrorException : Creating default object from empty value 

### ISSUE THREAD

**Issue by 0l1v3r5** [avored/laravel-ecommerce#504]
**Describe the bug**
I got this error when editing the image of an existing product. The product was registered during the integration of the demo data.

**To Reproduce**
  1.  composer create-project --prefer-dist avored/laravel-ecommerce avoredshop
  2.  Set up your Envirionment(.env) file
  3.  php artisan avored:install
  4.  php artisan avored:admin:make
  5.  Go to http://localhost/admin/login
  6.  Edit an old images product
  6.  See error

**Screenshots**
![🧨_Creating_default_object_from_empty_value](https://user-images.githubusercontent.com/29924640/96170228-9ef41380-0f23-11eb-9638-06168ded73d2.png)

**Comment by indpurvesh** [comment]
@0l1v3r5 

I just fixed this bug yesterday. After uploading another image and click save it was casing an issue.
Here is the commit:
`https://github.com/avored/framework/commit/6273b82c5074a888b67e6e46e10b9ea5789faf9f`

I am thinking of doing another minor release in next couple of day which include this and other issue of mix file doen't exist and etc.
