### ISSUE TITLE
Currency blade directive

### ISSUE THREAD

**Issue by indpurvesh** [avored/laravel-ecommerce#514]
We need to add a currency directive in blade which convert the product price to a nicely formatter currency with currency symbol and number_format too

    @currency(5000.34) => $5,000.34

**Comment by g1dra** [comment]
I can help with this issue.

**Comment by indpurvesh** [comment]
Sure thinks. 

Just add the blade directive into `https://github.com/avored/framework`. Just make sure please do a Pull request on `developed` branch.

**Comment by indpurvesh** [comment]
@g1dra 

Can you please create another provider here `https://github.com/avored/framework/tree/master/src/Support/Providers/BladePrvider.php` 

You can register the provider here.

`https://github.com/avored/framework/blob/master/src/AvoRedProvider.php#L28` in this class there is a property  `$providers`

**Comment by g1dra** [comment]
Ok. Tnx.

**Comment by g1dra** [comment]
I have few questions:
 From where do i get currency?  It will be used in directive?

**Comment by indpurvesh** [comment]
Here is the code to get the default currency.

    if (! Session::has('default_currency')) {
            $currency = $this->currencyRepository->getDefault();
        } 
     else  if (! Session::has('default_currency_symbol')) {
            $currency = $this->currencyRepository->getDefault();
     }

**Comment by korxz** [comment]
Is this still active issue?

**Comment by indpurvesh** [comment]
@korxz 

It's done.
Thanks for considering.
