### ISSUE TITLE
app.css cannot be located after installed the app

### ISSUE THREAD

**Issue by hxdev** [avored/laravel-ecommerce#516]
**Describe the bug**

**To Reproduce**
1. Follow all the steps at https://avored.com/docs/user/installation
2. Head to **https://local.htshop.com/admin/**
3. Layout is broken
4. Console showing: **https://local.htshop.com/admin/css/avored.app.css net::ERR_ABORTED 500 (Internal Server Error)**

**Screenshots**
[https://i.imgur.com/EjvCX9q.png](https://i.imgur.com/EjvCX9q.png)

**Comment by hxdev** [comment]
The cause is here https://github.com/avored/assets/commit/f9612412dbe60fe02900359c913db9c122c319f2#diff-287b44227f5dfb89b83a85b4e2a9569668e0191408af01b30ef8f8230f100eeaR32

But I'm not sure why the installation still use the old version.

**Comment by indpurvesh** [comment]
@hxdev 

Yes you right it should use the new way
Of adding the js and css . But I will try to look at them as soon as possible. Thanks for raising the issues. I will mark as a bug

**Comment by indpurvesh** [comment]
@hxdev 

Now i just added an unit test and its passing so hopefully from next release it wont be an issue.

**Comment by indpurvesh** [comment]
@hxdev 

just for your reference i have fixed the bug into `avored/assets` but then i did commit to the main branch but did not release it.

**Comment by marol1210** [comment]
@indpurvesh 

thanks for your done.

I have one question about this issue. 

I saw method registerAssets of  AssetsManager,  When register JS item , it add real file to item collection , but the file name is not the same as the one quoted in the script element of view page.

consequence nginx can't find the JS file ,  because the file is not exist.    at the moment i  just copy the JS file to web host dir.

**Comment by indpurvesh** [comment]
@marol1210 

Concept here is the Asset Collection contains only js_key => file_path as a collection.

Once it hit the route (/admin/js/js_key) with the js_key  then inside the controller we get the absolute path and controller pass the JS file content.

I get the idea from `https://github.com/livewire/livewire` package.  Try to understand how does @livewireScript blade tag is working.

**Comment by marol1210** [comment]
**thank you.**
**it's very helpful.**
