### ISSUE TITLE
No banner showing after installation

### ISSUE THREAD

**Issue by YeeJiaWei** [avored/laravel-ecommerce#523]
**Ideally we would expect you to raise a discussion on AvoRed Official Website **
https://avored.com/discussion/category/general

![image](https://user-images.githubusercontent.com/21292986/101261628-a5f51080-3773-11eb-9ce7-38a927c33d47.png)

After installation no banner is showing up

**Comment by blackLotus1998** [comment]
Problem 1
    - Installation request for avored/banner ^2.0 -> satisfiable by avored/banner[2.0].
    - avored/banner 2.0 requires avored/framework ~2.0 -> satisfiable by avored/framework[2.0, 2.1, 2.2, 2.3, 2.3.1, 2.3.2, 2.3.7, 2.3.7.2, 2.3.7.9, 2.3.8, 2.3.8.6, 2.7, 2.8, 2.8.1, 2.8.7, 2.8.8, 2.8.9, 2.9, 2.9.0.1, 2.9.2, 2.9.3] but these conflict with your requirement
s or minimum-stability.

this is error when i trying to install avored/banner

**Comment by indpurvesh** [comment]
Looks like i have missed to upgrade the `avored/framework` into banner modules `composer.json` file

**Comment by indpurvesh** [comment]
I think the issue here is different. Have you check in the admin => cms => page that contains the avored banner module widget?

**Comment by blackLotus1998** [comment]
after installation of updated version  the banner showing like this

**Comment by indpurvesh** [comment]
@blackLotus1998 

Looks like that the banner is rendered but the JS has some issue.
