### ISSUE TITLE
The variation product is not showing in the product list

### ISSUE THREAD

**Issue by blackLotus1998** [avored/laravel-ecommerce#527]
![image](https://user-images.githubusercontent.com/21292986/102010502-65038a00-3d79-11eb-96ed-121047df546a.png)
![image](https://user-images.githubusercontent.com/21292986/102010504-6b920180-3d79-11eb-9a34-09e47a27331c.png)

As title, the product is not showing

**Comment by indpurvesh** [comment]
@blackLotus1998 

Yes you right i am not queuing the variation product. But yes you are right if it's editable then update on that product gets bit easier to manage. 
I will think of adding that as a feature request.

**Comment by indpurvesh** [comment]
@blackLotus1998 

This one should be fixed.


<img width="1050" alt="Screen Shot 2020-12-17 at 4 24 47 pm" src="https://user-images.githubusercontent.com/4218702/102440078-6805bf80-4084-11eb-9213-f5f0da1e7d49.png">
