### ISSUE TITLE
Cannot require avored/banner

### ISSUE THREAD

**Issue by blackLotus1998** [avored/laravel-ecommerce#532]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires avored/banner ^2.4, found avored/banner[dev-developed, 1.0, ..., 1.7.2, 2.0, 2.1, 2.2] but it does not match the constraint.

**Comment by indpurvesh** [comment]
@blackLotus1998 Are you using module after installation or during installation?

**Comment by blackLotus1998** [comment]
During installation

**Comment by indpurvesh** [comment]
I will try again tonight or over the weekend to sort out the issue. Thanks for raising

**Comment by indpurvesh** [comment]
@blackLotus1998 

Try it now it should be fixed.

`composer create-project avored/laravel-ecommerce`
