### ISSUE TITLE
Demo User Error

### ISSUE THREAD

**Issue by bopclic** [avored/laravel-ecommerce#599]
I get the following error on accessing the home route for users yet the admin route works fine.

Symfony\Component\Debug\Exception\FatalThrowableError

method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given (View: C:\xampp\htdocs\laravel-ecommerce\resources\views\home.blade.php)

**Comment by indpurvesh** [comment]
@bopclic  thanks but i am ditching almost all the code and redoing it with GraphQL as backend and front with initially vue3 then react and angular frontend. As i am not very fast with vue3 and typescript it's taking longer. At this stage, the basic app is almost ready including the frontend and backend.
