### ISSUE TITLE
CORS Setup for this Project / Cross Origin Issue

### ISSUE THREAD

**Issue by tommyready** [avored/laravel-ecommerce#615]
Can someone please explain how to configure CORS? I cannot get it to work.  Generic CORS cross origin blocked error.  Any help would be great, thanks in advance.

**Comment by indpurvesh** [comment]
You can open your `config/cors.php` file of your backend app then then replace the line like below.

     'allowed_origins' => ['http://localhost:8080'],

**Comment by indpurvesh** [comment]
just updated the docs too. I am closing this issue. Let me know anyone has still having any trouble.
