### ISSUE TITLE
Fix bugs etc..

### ISSUE THREAD

**Issue by bloggervista** [avored/laravel-ecommerce#68]
There are many things that don't work and simply throws error like invalid exception on various routes. Can we fix it?

**Comment by bloggervista** [comment]
Just install fresh laravel and if we browse various routes like tax etc.. and various config option we get such errors

**Comment by dakshhmehta** [comment]
Thanks for input, I just joined the project today, and will be looking forward to actively participate in this project. Could you please list out the error or mention the URI on which you are getting an error?

**Comment by bloggervista** [comment]
@dakshhmehta  you can browse to tax routes etc after login it will show 404 like that.

**Comment by indpurvesh** [comment]
Tax routes is only for Ajax and backend so it won’t work as a get request of php
