### ISSUE TITLE
Following Coding Standard

### ISSUE THREAD

**Issue by dakshhmehta** [avored/laravel-ecommerce#72]
Hello,

as you might have noticed, I recently discovered this package and started loving this. However, I see many of the files, database seeder, and folder structure is getting reintialised and right now is completely missing from the code. For example, due to seeders missing, not able to install or even register a first admin user and get started working on a project.

This won't allow us to work on the project and contribute to it.

So, my suggestion would be to lets follow Gitflow and proper tagging for release so we don't break anything while actively working on this project.

#LetsMakeItBig

Happy Coding!

Thanks,
Daksh

**Comment by indpurvesh** [comment]
@dakshhmehta Sorry it was my mistake and i did remove install module from composer that's why we you have faced the issue of installation. If you try again it should be ok to work and thanks for fixing the order_statues bug.

**Comment by darron1217** [comment]
@indpurvesh 
How about using those popular plugins for modulation?
https://github.com/caffeinated/modules
https://github.com/caffeinated/themes

It's external pakage, but we can copy the style from it :)

**Comment by ghermans** [comment]
@indpurvesh maybe this can help https://github.com/phpro/grumphp

**Comment by indpurvesh** [comment]
It looks very interesting. thanks @ghermans
